import Link from "next/link";
import { notFound } from "next/navigation";
import { CategoryForm } from "@/components/dashboard/category-form";
import { ProductForm } from "@/components/dashboard/product-form";
import { ProductMedia } from "@/components/dashboard/product-media";
import { ProductGrid } from "@/components/public/product-grid";

export const dynamic = "force-dynamic";

export default async function Phase2APreview({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  if (process.env.NODE_ENV === "production") notFound();
  const { fixtureCatalogueProducts, fixtureCategories, fixtureProduct } = await import("@/lib/catalogue/dev-fixtures");
  const params = await searchParams;
  const view = typeof params.view === "string" ? params.view : "lists";
  return <main className="min-h-screen bg-limestone px-4 py-6 text-graphite sm:px-6"><div className="mx-auto max-w-6xl"><div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Offline UI preview.</strong> Development fixtures are isolated from production queries. Actions are disabled.</div><div className="mt-6 flex flex-wrap gap-2">{["lists", "category-form", "product-form", "catalogue"].map((item) => <Link key={item} href={`/dev/phase2a?view=${item}`} className={`min-h-11 rounded-md border px-4 py-3 text-sm ${view === item ? "border-graphite bg-graphite text-white" : "border-line bg-paper"}`}>{item.replace("-", " ")}</Link>)}</div>
    <div className="mt-8" inert>{view === "category-form" ? <div className="mx-auto max-w-4xl"><h1 className="mb-6 text-3xl font-semibold">Edit category</h1><CategoryForm category={fixtureCategories[0]} /></div> : view === "product-form" ? <div className="mx-auto max-w-5xl"><h1 className="mb-6 text-3xl font-semibold">Edit product</h1><ProductForm product={fixtureProduct} categories={fixtureCategories.map(({ id, name, is_active }) => ({ id, name, is_active }))} /><div className="mt-6"><ProductMedia productId={fixtureProduct.id} images={[]} /></div></div> : view === "catalogue" ? <div><h1 className="mb-6 text-4xl font-semibold tracking-[-0.05em]">Product catalogue</h1><ProductGrid products={fixtureCatalogueProducts} /></div> : <div className="grid gap-8 lg:grid-cols-2"><section><h1 className="text-2xl font-semibold">Category list</h1><div className="mt-4 divide-y divide-line rounded-lg border border-line bg-paper">{fixtureCategories.map((category) => <article key={category.id} className="flex items-center justify-between gap-4 p-4"><div><h2 className="font-semibold">{category.name}</h2><p className="text-sm text-stone">/{category.slug}</p></div><span className={`rounded-sm px-2 py-1 text-xs ${category.is_active ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{category.is_active ? "Active" : "Inactive"}</span></article>)}</div></section><section><h1 className="text-2xl font-semibold">Product list</h1><div className="mt-4 divide-y divide-line rounded-lg border border-line bg-paper">{fixtureCatalogueProducts.map((product) => <article key={product.id} className="p-4"><div className="flex items-start justify-between gap-4"><div><h2 className="font-semibold">{product.name}</h2><p className="text-sm text-stone">{product.product_code} · {product.category.name}</p></div><span className="rounded-sm bg-amber-50 px-2 py-1 text-xs text-amber-800">Draft</span></div><div className="mt-4 flex gap-5 text-sm font-medium"><span>Edit product</span><span>Publish</span><span className="text-red-700">Archive</span></div></article>)}</div></section></div>}</div></div></main>;
}
