import Link from "next/link";
import { ArrowLeft, Pencil, Phone, Plus, Send } from "lucide-react";
import { notFound } from "next/navigation";
import { assignCustomerAction, setCustomerArchivedAction } from "@/app/dashboard/customers/actions";
import { PageHeading } from "@/components/ui/page-heading";
import { requireModuleAccess } from "@/lib/auth/dal";
import { enquiryReference, followUpStatusLabel, formatDate, formatPhoneLink, formatWhatsAppLink, statusLabel } from "@/lib/crm/presentation";
import { getCustomer, getCustomerWorkspace, getStaffDirectory } from "@/lib/crm/queries";

function Detail({ label, value }: { label: string; value?: string | null }) { return <div><dt className="text-xs text-stone">{label}</dt><dd className="mt-1 text-sm leading-6">{value || "—"}</dd></div>; }

export default async function CustomerPage({ params }: PageProps<"/dashboard/customers/[id]">) {
  const { id } = await params;
  const [profile, customer, workspace, staff] = await Promise.all([requireModuleAccess("customers"), getCustomer(id), getCustomerWorkspace(id), getStaffDirectory()]);
  if (!customer) notFound();
  const canEdit = ["admin", "sales"].includes(profile.role);
  const phoneHref = formatPhoneLink(customer.phone);
  const whatsappHref = formatWhatsAppLink(customer.whatsapp_number || customer.phone);
  return <div className="space-y-7"><Link href="/dashboard/customers" className="inline-flex min-h-11 items-center gap-2 text-sm text-stone"><ArrowLeft size={16} />Back to customers</Link><PageHeading title={customer.name} description={[customer.company_name, customer.area, customer.emirate].filter(Boolean).join(" · ") || "Customer record"} action={canEdit ? <div className="flex flex-wrap gap-2"><Link href={`/dashboard/enquiries/new?customer=${id}`} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Plus size={16} />New enquiry</Link><Link href={`/dashboard/customers/${id}/edit`} className="inline-flex min-h-11 items-center gap-2 rounded-md border border-line bg-paper px-4 text-sm font-medium"><Pencil size={16} />Edit</Link></div> : undefined} />
    <div className="flex flex-wrap gap-2">{phoneHref && <a href={phoneHref} className="inline-flex min-h-11 items-center gap-2 rounded-md border border-line bg-paper px-4 text-sm font-medium"><Phone size={16} />Call</a>}{whatsappHref && <a href={whatsappHref} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center gap-2 rounded-md border border-line bg-paper px-4 text-sm font-medium"><Send size={16} />WhatsApp</a>}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(18rem,0.7fr)]"><div className="space-y-6"><section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Customer information</h2><dl className="mt-5 grid gap-x-8 gap-y-5 sm:grid-cols-2"><Detail label="Phone" value={customer.phone} /><Detail label="WhatsApp" value={customer.whatsapp_number} /><Detail label="Email" value={customer.email} /><Detail label="Company" value={customer.company_name} /><Detail label="Address" value={customer.address} /><Detail label="Area / emirate" value={[customer.area, customer.emirate].filter(Boolean).join(", ")} /><Detail label="Source" value={customer.source} /><Detail label="Assigned salesperson" value={customer.assigned?.full_name || "Unassigned"} /></dl>{customer.notes && <div className="mt-6 border-t border-line pt-5"><p className="text-xs text-stone">Internal notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{customer.notes}</p></div>}</section>
      <section><div className="flex items-end justify-between"><div><h2 className="text-lg font-semibold">Enquiries</h2><p className="mt-1 text-sm text-stone">Every opportunity linked to this customer.</p></div></div><div className="mt-4 divide-y divide-line border-y border-line bg-paper sm:rounded-lg sm:border">{workspace.enquiries.length ? workspace.enquiries.map((enquiry) => <Link key={enquiry.id} href={`/dashboard/enquiries/${enquiry.id}`} className="flex items-center justify-between gap-4 px-4 py-4"><div className="min-w-0"><p className="font-semibold">{enquiryReference(enquiry.enquiry_number)}</p><p className="truncate text-sm text-stone">{enquiry.subject || enquiry.product?.name || "General enquiry"}</p></div><div className="shrink-0 text-right"><p className="text-sm">{statusLabel(enquiry.status)}</p><p className="mt-1 text-xs text-stone">{formatDate(enquiry.created_at)}</p></div></Link>) : <p className="px-4 py-8 text-center text-sm text-stone">No enquiries linked yet.</p>}</div></section>
      <section><h2 className="text-lg font-semibold">Follow-ups</h2><div className="mt-4 divide-y divide-line border-y border-line bg-paper sm:rounded-lg sm:border">{workspace.followUps.length ? workspace.followUps.map((task) => <div key={task.id} className="flex items-start justify-between gap-4 px-4 py-4"><div><p className="text-sm font-medium">{task.title}</p><p className="mt-1 text-xs text-stone">{task.assigned?.full_name || "Unassigned"}</p></div><div className="text-right text-xs"><p>{formatDate(task.due_at, true)}</p><p className="mt-1 text-stone">{followUpStatusLabel(task.status)}</p></div></div>) : <p className="px-4 py-8 text-center text-sm text-stone">No follow-ups yet.</p>}</div></section>
      <section className="border-y border-dashed border-line py-5"><h2 className="text-base font-semibold">Later workflow</h2><p className="mt-2 text-sm text-stone">Site visits, quotations, projects, and payments will attach to this same customer record in later phases.</p></section></div>
      <aside className="space-y-5"><section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Ownership</h2>{profile.role === "admin" ? <form action={assignCustomerAction} className="mt-4 space-y-3"><input type="hidden" name="id" value={id} /><select name="assigned_to" defaultValue={customer.assigned_to || ""} className="min-h-11 w-full rounded-md border border-line bg-paper px-3 text-base"><option value="">Unassigned</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select><button className="min-h-10 text-sm font-medium text-brass-dark">Save assignment</button></form> : <p className="mt-3 text-sm text-stone">{customer.assigned?.full_name || "Unassigned"}</p>}{profile.role === "admin" && <form action={setCustomerArchivedAction} className="mt-5 border-t border-line pt-4"><input type="hidden" name="id" value={id} /><input type="hidden" name="archived" value={String(!customer.archived_at)} /><button className="min-h-10 text-sm font-medium text-red-700">{customer.archived_at ? "Reactivate customer" : "Archive customer"}</button></form>}</section>
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Customer activity</h2><ol className="mt-5 border-l border-line pl-5">{workspace.activity.length ? workspace.activity.map((item) => <li key={item.id} className="relative pb-5 last:pb-0"><span className="absolute -left-[1.43rem] top-1 size-2 rounded-full bg-brass" /><p className="text-sm font-medium">{item.event_type.replaceAll(".", " ").replace(/^./, (letter) => letter.toUpperCase())}</p><p className="mt-1 text-xs text-stone">{item.actor?.full_name || "System"} · {formatDate(item.created_at, true)}</p></li>) : <li className="text-sm text-stone">No activity recorded.</li>}</ol></section></aside></div>
  </div>;
}
