import Image from "next/image";
import Link from "next/link";
import { Boxes, Pencil, Plus } from "lucide-react";
import { archiveProductAction, setProductPublishedAction } from "@/app/dashboard/products/actions";
import { EmptyState } from "@/components/ui/empty-state";
import { DemoDisabledNotice } from "@/components/dashboard/demo-disabled-notice";
import { PageHeading } from "@/components/ui/page-heading";
import { requireModuleAccess } from "@/lib/auth/dal";
import { getAdminProducts, getCategoryOptions } from "@/lib/catalogue/admin-queries";
import { presentPrice } from "@/lib/catalogue/presentation";
import { isDemoMode } from "@/lib/demo-mode-server";

function ProductThumb({ name, url }: { name: string; url?: string | null }) {
  return <div className="relative size-14 shrink-0 overflow-hidden rounded-md bg-limestone">{url ? <Image src={url} alt={`${name} thumbnail`} fill sizes="56px" className="object-cover" /> : <div className="grid size-full place-items-center text-[10px] text-stone">No image</div>}</div>;
}

export default async function ProductsDashboardPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [profile, params, categories] = await Promise.all([requireModuleAccess("products"), searchParams, getCategoryOptions()]);
  const filters = Object.fromEntries(Object.entries(params).filter((entry): entry is [string, string] => typeof entry[1] === "string"));
  const products = await getAdminProducts(filters);
  const canManage = profile.role === "admin" && !isDemoMode();
  return <div className="space-y-7"><PageHeading title="Products" description="Manage catalogue content, pricing visibility, publication, and product media." action={canManage ? <Link href="/dashboard/products/new" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Plus size={17} />New product</Link> : undefined} />
    {isDemoMode() && <DemoDisabledNotice>Product editing, publishing, archiving, and media uploads are disabled in the public demo.</DemoDisabledNotice>}
    <form className="grid gap-3 border-y border-line bg-paper py-4 sm:rounded-lg sm:border sm:p-4 md:grid-cols-2 2xl:grid-cols-[minmax(12rem,1fr)_12rem_11rem_10rem_10rem_auto]"><input name="search" defaultValue={filters.search || ""} aria-label="Search products" placeholder="Search product or SKU" className="min-h-11 rounded-md border border-line px-3 text-base" /><select name="category" defaultValue={filters.category || ""} aria-label="Filter by category" className="min-h-11 rounded-md border border-line bg-paper px-3 text-base"><option value="">All categories</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select><select name="published" defaultValue={filters.published || ""} aria-label="Filter publication" className="min-h-11 rounded-md border border-line bg-paper px-3 text-base"><option value="">Any publication</option><option value="published">Published</option><option value="draft">Unpublished</option></select><select name="featured" defaultValue={filters.featured || ""} aria-label="Filter featured" className="min-h-11 rounded-md border border-line bg-paper px-3 text-base"><option value="">Any feature state</option><option value="featured">Featured</option><option value="standard">Standard</option></select><select name="state" defaultValue={filters.state || ""} aria-label="Filter archive state" className="min-h-11 rounded-md border border-line bg-paper px-3 text-base"><option value="">Current</option><option value="archived">Archived</option></select><button className="min-h-11 rounded-md border border-line bg-limestone px-4 text-sm font-medium">Apply</button></form>
    {products.length === 0 ? <EmptyState icon={Boxes} title="No products found" description={Object.values(filters).some(Boolean) ? "Adjust the filters or create a product." : "Create the first product after its category is ready."} /> : <>
      <div className="hidden overflow-x-auto rounded-lg border border-line bg-paper lg:block"><table className="min-w-[980px] w-full text-left text-sm"><thead className="border-b border-line bg-limestone text-xs text-stone"><tr><th className="px-4 py-3 font-medium">Product</th><th className="px-4 py-3 font-medium">SKU</th><th className="px-4 py-3 font-medium">Category</th><th className="px-4 py-3 font-medium">Pricing</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Updated</th><th className="px-4 py-3 font-medium">Actions</th></tr></thead><tbody className="divide-y divide-line">{products.map((product) => <tr key={product.id}><td className="px-4 py-3"><div className="flex items-center gap-3"><ProductThumb name={product.name} url={product.images[0]?.url} /><div className="min-w-0"><p className="max-w-56 truncate font-medium">{product.name}</p>{product.is_featured && <p className="text-xs text-brass-dark">Featured</p>}</div></div></td><td className="px-4 py-3 text-stone">{product.product_code || "—"}</td><td className="px-4 py-3">{product.category?.name || "Uncategorised"}</td><td className="px-4 py-3">{presentPrice(product.pricing_mode, product.price) || "Hidden"}</td><td className="px-4 py-3"><span className={`rounded-sm px-2 py-1 text-xs ${product.archived_at ? "bg-stone/10 text-stone" : product.is_published ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{product.archived_at ? "Archived" : product.is_published ? "Published" : "Draft"}</span></td><td className="px-4 py-3 text-stone">{new Intl.DateTimeFormat("en-AE", { dateStyle: "medium" }).format(new Date(product.updated_at))}</td><td className="px-4 py-3"><div className="flex items-center gap-3">{canManage && <Link href={`/dashboard/products/${product.id}/edit`} className="inline-flex min-h-10 items-center gap-1 font-medium"><Pencil size={14} />Edit</Link>}{product.is_published && !product.archived_at && <Link href={`/products/${product.slug}`} className="min-h-10 py-2 font-medium text-brass-dark">View</Link>}{canManage && !product.archived_at && <form action={setProductPublishedAction}><input type="hidden" name="id" value={product.id} /><input type="hidden" name="published" value={String(!product.is_published)} /><button className="min-h-10 text-xs font-medium">{product.is_published ? "Unpublish" : "Publish"}</button></form>}{canManage && !product.archived_at && <form action={archiveProductAction}><input type="hidden" name="id" value={product.id} /><button className="min-h-10 text-xs font-medium text-red-700">Archive</button></form>}</div></td></tr>)}</tbody></table></div>
      <div className="space-y-3 lg:hidden">{products.map((product) => <article key={product.id} className="border-y border-line bg-paper px-4 py-4 sm:rounded-lg sm:border"><div className="flex gap-3"><ProductThumb name={product.name} url={product.images[0]?.url} /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h2 className="truncate font-semibold">{product.name}</h2><p className="truncate text-xs text-stone">{product.product_code || "No SKU"} · {product.category?.name || "Uncategorised"}</p></div><span className={`shrink-0 rounded-sm px-2 py-1 text-xs ${product.is_published && !product.archived_at ? "bg-emerald-50 text-emerald-800" : "bg-stone/10 text-stone"}`}>{product.archived_at ? "Archived" : product.is_published ? "Published" : "Draft"}</span></div><p className="mt-2 text-sm">{presentPrice(product.pricing_mode, product.price) || "Price hidden"}</p></div></div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm">{canManage && <Link href={`/dashboard/products/${product.id}/edit`} className="min-h-10 py-2 font-medium">Edit product</Link>}{product.is_published && !product.archived_at && <Link href={`/products/${product.slug}`} className="min-h-10 py-2 font-medium text-brass-dark">View public page</Link>}{canManage && !product.archived_at && <form action={setProductPublishedAction}><input type="hidden" name="id" value={product.id} /><input type="hidden" name="published" value={String(!product.is_published)} /><button className="min-h-10 font-medium">{product.is_published ? "Unpublish" : "Publish"}</button></form>}{canManage && !product.archived_at && <form action={archiveProductAction}><input type="hidden" name="id" value={product.id} /><button className="min-h-10 font-medium text-red-700">Archive</button></form>}</div></article>)}</div>
    </>}
  </div>;
}
