import Link from "next/link";
import { Archive, Pencil, Plus } from "lucide-react";
import { archiveCategoryAction, setCategoryActiveAction, setCategoryOrderAction } from "@/app/dashboard/categories/actions";
import { PageHeading } from "@/components/ui/page-heading";
import { EmptyState } from "@/components/ui/empty-state";
import { DemoDisabledNotice } from "@/components/dashboard/demo-disabled-notice";
import { requireModuleAccess } from "@/lib/auth/dal";
import { getAdminCategories } from "@/lib/catalogue/admin-queries";
import { isDemoMode } from "@/lib/demo-mode-server";

export default async function CategoriesPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [profile, params] = await Promise.all([requireModuleAccess("categories"), searchParams]);
  const search = typeof params.search === "string" ? params.search : "";
  const state = typeof params.state === "string" ? params.state : "";
  const categories = await getAdminCategories({ search, state });
  const canManage = profile.role === "admin" && !isDemoMode();

  return <div className="space-y-7">
    <PageHeading title="Categories" description="Organise the public catalogue, visibility, search metadata, and display order." action={canManage ? <Link href="/dashboard/categories/new" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Plus size={17} />New category</Link> : undefined} />
    {isDemoMode() && <DemoDisabledNotice>Catalogue editing, activation, archiving, and uploads are disabled in the public demo.</DemoDisabledNotice>}
    <form className="grid gap-3 border-y border-line bg-paper py-4 sm:rounded-lg sm:border sm:p-4 md:grid-cols-[minmax(12rem,1fr)_12rem_auto]"><label className="sr-only" htmlFor="category-search">Search categories</label><input id="category-search" name="search" defaultValue={search} placeholder="Search name or slug" className="min-h-11 rounded-md border border-line px-3 text-base" /><label className="sr-only" htmlFor="category-state">Category state</label><select id="category-state" name="state" defaultValue={state} className="min-h-11 rounded-md border border-line bg-paper px-3 text-base"><option value="">Current categories</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="archived">Archived</option></select><button className="min-h-11 rounded-md border border-line bg-limestone px-5 text-sm font-medium">Apply filters</button></form>
    {categories.length === 0 ? <EmptyState icon={Archive} title="No categories found" description={search || state ? "Adjust the filters or create a category." : "Create the first category when the real catalogue structure is ready."} /> : <>
      <div className="hidden overflow-hidden rounded-lg border border-line bg-paper md:block"><table className="w-full table-fixed text-left text-sm"><thead className="border-b border-line bg-limestone text-xs text-stone"><tr><th className="w-[31%] px-4 py-3 font-medium">Category</th><th className="w-[13%] px-4 py-3 font-medium">Status</th><th className="w-[17%] px-4 py-3 font-medium">Order</th><th className="w-[16%] px-4 py-3 font-medium">Updated</th><th className="px-4 py-3 font-medium">Actions</th></tr></thead><tbody className="divide-y divide-line">{categories.map((category) => <tr key={category.id}>
        <td className="px-4 py-3"><p className="truncate font-medium">{category.name}</p><p className="truncate text-xs text-stone">/{category.slug}</p></td>
        <td className="px-4 py-3"><span className={`inline-flex rounded-sm px-2 py-1 text-xs ${category.archived_at ? "bg-stone/10 text-stone" : category.is_active ? "bg-emerald-50 text-emerald-800" : "bg-amber-50 text-amber-800"}`}>{category.archived_at ? "Archived" : category.is_active ? "Active" : "Inactive"}</span></td>
        <td className="px-4 py-3">{canManage && !category.archived_at ? <form action={setCategoryOrderAction} className="flex items-center gap-2"><input type="hidden" name="id" value={category.id} /><input name="sort_order" aria-label={`Sort order for ${category.name}`} type="number" defaultValue={category.sort_order} className="min-h-10 w-20 rounded-md border border-line px-2 text-base" /><button className="min-h-10 text-xs font-medium text-brass-dark">Save</button></form> : category.sort_order}</td>
        <td className="px-4 py-3 text-stone">{new Intl.DateTimeFormat("en-AE", { dateStyle: "medium" }).format(new Date(category.updated_at))}</td>
        <td className="px-4 py-3"><div className="flex items-center gap-3">{canManage ? <><Link href={`/dashboard/categories/${category.id}/edit`} className="inline-flex min-h-10 items-center gap-1 font-medium"><Pencil size={14} />Edit</Link>{!category.archived_at && <><form action={setCategoryActiveAction}><input type="hidden" name="id" value={category.id} /><input type="hidden" name="active" value={String(!category.is_active)} /><button className="min-h-10 text-xs font-medium text-brass-dark">{category.is_active ? "Deactivate" : "Activate"}</button></form><form action={archiveCategoryAction}><input type="hidden" name="id" value={category.id} /><button className="min-h-10 text-xs font-medium text-red-700">Archive</button></form></>}</> : <span className="text-xs text-stone">Read only</span>}</div></td>
      </tr>)}</tbody></table></div>
      <div className="space-y-3 md:hidden">{categories.map((category) => <article key={category.id} className="border-y border-line bg-paper px-4 py-4 sm:rounded-lg sm:border"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold">{category.name}</h2><p className="truncate text-xs text-stone">/{category.slug}</p></div><span className={`rounded-sm px-2 py-1 text-xs ${category.is_active && !category.archived_at ? "bg-emerald-50 text-emerald-800" : "bg-stone/10 text-stone"}`}>{category.archived_at ? "Archived" : category.is_active ? "Active" : "Inactive"}</span></div><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm">{canManage ? <><Link href={`/dashboard/categories/${category.id}/edit`} className="min-h-10 font-medium text-graphite">Edit category</Link>{!category.archived_at && <><form action={setCategoryActiveAction}><input type="hidden" name="id" value={category.id} /><input type="hidden" name="active" value={String(!category.is_active)} /><button className="min-h-10 font-medium text-brass-dark">{category.is_active ? "Deactivate" : "Activate"}</button></form><form action={archiveCategoryAction}><input type="hidden" name="id" value={category.id} /><button className="min-h-10 font-medium text-red-700">Archive</button></form></>}</> : <span className="text-stone">Read only</span>}</div></article>)}</div>
    </>}
  </div>;
}
