import Link from "next/link";
import { AlertTriangle, ArrowLeft, CalendarClock, Download, Plus, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { CancelMilestoneForm, MilestoneForm, PlanControls } from "@/components/dashboard/payment-controls";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusNotice } from "@/components/ui/status-notice";
import { requireModuleAccess } from "@/lib/auth/dal";
import { formatDate } from "@/lib/crm/presentation";
import { formatMoney } from "@/lib/quotations/money";
import { paymentMethodLabel, paymentPlanLabel, paymentStatusClass, paymentStatusLabel } from "@/lib/payments/presentation";
import { getFinanceProject, getMilestoneSummaries, getProjectFinanceSummary, getProjectReceipts } from "@/lib/payments/queries";

export default async function ProjectPaymentsPage({ params }: PageProps<"/dashboard/payments/projects/[id]">) {
  const { id } = await params;
  await requireModuleAccess("payments");
  const [project, summary, milestones, receipts] = await Promise.all([getFinanceProject(id), getProjectFinanceSummary(id), getMilestoneSummaries(id), getProjectReceipts(id)]);
  if (!project || !summary) notFound();
  const liveMilestones = milestones.filter((item) => !item.cancelled_at);
  const reconciled = Number(summary.planned) === Number(summary.project_value) && liveMilestones.length > 0;
  return <div className="space-y-7">
    <Link href="/dashboard/payments" className="inline-flex min-h-11 items-center gap-2 text-sm text-stone"><ArrowLeft size={16} />Back to payments</Link>
    <PageHeading title={project.project_number} description={`${project.customer?.name || "Customer"} · payment plan and receipt ledger`} action={project.payment_plan_status === "active" ? <Link href={`/dashboard/payments/new?project=${project.id}`} className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Plus size={16} />Record payment</Link> : undefined} />
    <section className="overflow-hidden rounded-lg bg-graphite text-white">
      <dl className="grid grid-cols-2 lg:grid-cols-5">{[
        ["Project value", formatMoney(summary.project_value, summary.currency)],
        ["Planned", formatMoney(summary.planned, summary.currency)],
        ["Received", formatMoney(summary.received, summary.currency)],
        ["Outstanding", formatMoney(summary.outstanding, summary.currency)],
        ["Overdue", formatMoney(summary.overdue, summary.currency)],
      ].map(([label,value],index) => <div key={label} className={`border-white/10 px-4 py-5 ${index % 2 === 0 ? "border-r lg:border-r" : ""} ${index < 4 ? "border-b lg:border-b-0 lg:border-r" : ""}`}><dt className="text-[10px] uppercase tracking-[0.16em] text-white/40">{label}</dt><dd className={`mt-2 truncate text-lg font-semibold ${label === "Overdue" && summary.overdue > 0 ? "text-red-300" : ""}`}>{value}</dd></div>)}</dl>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t border-white/10 px-4 py-3 text-xs text-white/55"><span>{summary.paid_percent}% received</span><span>Next due {formatDate(summary.next_due_date)}</span><span className={`rounded-sm border px-2 py-1 ${paymentStatusClass(summary.plan_status)}`}>{paymentPlanLabel(summary.plan_status)}</span></div>
    </section>
    {project.status === "completed" && summary.outstanding > 0 ? <StatusNotice tone="error" title="Completed project has an outstanding balance"><p>Operational completion remains valid, but Accounts should follow up on {formatMoney(summary.outstanding, summary.currency)}.</p></StatusNotice> : null}
    {project.payment_plan_status === "draft" && !reconciled ? <StatusNotice title="Draft plan is not reconciled"><p>Planned milestones differ from project value by {formatMoney(Math.abs(summary.project_value - summary.planned), summary.currency)}. You may keep saving the draft, but activation remains blocked.</p></StatusNotice> : null}
    <div className="grid gap-7 xl:grid-cols-[minmax(0,1.45fr)_minmax(19rem,0.55fr)]"><div className="space-y-7">
      <section><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">Milestone ledger</h2><p className="mt-1 text-sm text-stone">Schedule, authoritative receipts, and remaining balance per milestone.</p></div><span className="text-xs text-stone">{liveMilestones.length} live</span></div>
        <div className="mt-4 space-y-3">{milestones.length ? milestones.map((milestone) => <article key={milestone.milestone_id} className={`rounded-lg border bg-paper p-4 sm:p-5 ${milestone.cancelled_at ? "border-line opacity-65" : milestone.status === "overdue" ? "border-red-200" : "border-line"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className={`font-semibold ${milestone.cancelled_at ? "line-through" : ""}`}>{milestone.name}</p>{milestone.description ? <p className="mt-1 text-sm text-stone">{milestone.description}</p> : null}<p className="mt-1 text-xs text-stone">{milestone.milestone_type === "percentage" ? `${milestone.percentage}% of project` : "Fixed amount"} · due {formatDate(milestone.due_date)}</p></div><span className={`rounded-sm border px-2 py-1 text-xs ${paymentStatusClass(milestone.status)}`}>{paymentStatusLabel(milestone.status)}</span></div><dl className="mt-4 grid grid-cols-3 gap-3 border-t border-line pt-4 text-sm"><div><dt className="text-xs text-stone">Due</dt><dd className="mt-1 font-semibold">{formatMoney(milestone.amount_due, summary.currency)}</dd></div><div><dt className="text-xs text-stone">Received</dt><dd className="mt-1">{formatMoney(milestone.received, summary.currency)}</dd></div><div><dt className="text-xs text-stone">Balance</dt><dd className={`mt-1 font-semibold ${milestone.status === "overdue" ? "text-red-700" : ""}`}>{formatMoney(milestone.outstanding, summary.currency)}</dd></div></dl>{milestone.notes ? <p className="mt-3 text-xs text-stone">Note: {milestone.notes}</p> : null}{milestone.cancellation_reason ? <p className="mt-3 text-xs text-red-700">Cancelled: {milestone.cancellation_reason}</p> : null}{project.payment_plan_status === "draft" && !milestone.cancelled_at ? <details className="mt-4 border-t border-line pt-3"><summary className="min-h-10 cursor-pointer py-2 text-sm font-semibold text-brass-dark">Edit milestone</summary><div className="pt-3"><MilestoneForm projectId={project.id} milestone={milestone} /><CancelMilestoneForm milestoneId={milestone.milestone_id} projectId={project.id} /></div></details> : null}</article>) : <p className="rounded-lg border border-line bg-paper px-5 py-9 text-center text-sm text-stone">No milestones yet. Build a draft schedule below.</p>}</div>
      </section>
      {project.payment_plan_status === "draft" ? <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Add milestone</h2><p className="mt-1 text-sm text-stone">Percentage amounts are calculated from {formatMoney(project.project_value, project.currency)} by Postgres.</p><div className="mt-5"><MilestoneForm projectId={project.id} nextOrder={(liveMilestones.at(-1)?.sort_order || 0) + 10} /></div></section> : null}
      <section><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">Receipt history</h2><p className="mt-1 text-sm text-stone">Posted receipts remain visible even when voided.</p></div></div><div className="mt-4 divide-y divide-line rounded-lg border border-line bg-paper">{receipts.length ? receipts.map((receipt) => <article key={receipt.id} className="grid gap-2 px-4 py-4 sm:grid-cols-[11rem_minmax(0,1fr)_9rem_7rem_3rem] sm:items-center"><div><Link href={`/dashboard/payments/${receipt.id}`} className={`font-semibold text-brass-dark ${receipt.voided_at ? "line-through text-stone" : ""}`}>{receipt.receipt_number}</Link><p className="text-xs text-stone">{formatDate(receipt.received_date)}</p></div><div><p className="text-sm">{receipt.milestone?.name || "Unlinked milestone"}</p><p className="text-xs text-stone">{paymentMethodLabel(receipt.payment_method)}{receipt.reference_number ? ` · ${receipt.reference_number}` : ""}</p></div><p className={`text-sm font-semibold sm:text-right ${receipt.voided_at ? "line-through text-stone" : ""}`}>{formatMoney(receipt.amount_received, summary.currency)}</p><span className={`text-xs sm:text-right ${receipt.voided_at ? "text-red-700" : "text-stone"}`}>{receipt.voided_at ? "Void" : `${receipt.proofs.length} proof${receipt.proofs.length === 1 ? "" : "s"}`}</span><Link href={`/dashboard/payments/${receipt.id}/pdf`} target="_blank" aria-label={`View PDF for ${receipt.receipt_number}`} className="grid size-10 place-items-center rounded-md border border-line text-brass-dark"><Download size={15} /></Link></article>) : <p className="px-5 py-9 text-center text-sm text-stone">No receipts posted.</p>}</div></section>
    </div><aside className="space-y-5">
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Plan control</h2><p className="mt-2 text-sm leading-6 text-stone">{project.payment_plan_status === "draft" ? "Draft milestones can be revised or cancelled. Activation permanently locks the schedule." : project.payment_plan_status === "active" ? "The schedule is locked while Accounts posts receipts." : "This plan is closed to further mutation."}</p><div className="mt-5"><PlanControls projectId={project.id} planStatus={project.payment_plan_status} reconciled={reconciled} /></div></section>
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Next financial action</h2><div className="mt-4 flex gap-3"><CalendarClock size={17} className="mt-0.5 shrink-0 text-brass-dark" /><div><p className="text-sm font-medium">{summary.overdue > 0 ? "Overdue follow-up" : summary.next_due_date ? "Upcoming milestone" : "No open milestone"}</p><p className={`mt-1 text-sm ${summary.overdue > 0 ? "text-red-700" : "text-stone"}`}>{summary.overdue > 0 ? `${formatMoney(summary.overdue, summary.currency)} is past due.` : `Next due ${formatDate(summary.next_due_date)}.`}</p></div></div>{project.payment_plan_status === "active" && summary.outstanding > 0 ? <Link href={`/dashboard/payments/new?project=${project.id}`} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md bg-brass-dark px-4 text-sm font-semibold text-white"><ReceiptText size={16} />Record receipt</Link> : null}</section>
      <section className="rounded-lg border border-line bg-limestone p-5"><div className="flex gap-3"><AlertTriangle size={17} className="mt-0.5 shrink-0 text-brass-dark" /><p className="text-xs leading-5 text-stone">Project completion is operationally independent. Any remaining balance is shown as a warning, not a completion blocker.</p></div></section>
    </aside></div>
  </div>;
}
