import Link from "next/link";
import { ArrowLeft, Check, Clock3, Phone, Send } from "lucide-react";
import { notFound } from "next/navigation";
import { assignEnquiryAction, cancelFollowUpAction, completeFollowUpAction, markContactedAction, rescheduleFollowUpAction } from "@/app/dashboard/enquiries/actions";
import { EnquiryEditor, EnquiryNoteForm, FollowUpForm } from "@/components/dashboard/enquiry-controls";
import { PageHeading } from "@/components/ui/page-heading";
import { requireModuleAccess } from "@/lib/auth/dal";
import { activityLabel, enquiryReference, followUpStatusLabel, formatDate, formatPhoneLink, formatWhatsAppLink, priorityClass, priorityLabel, statusLabel } from "@/lib/crm/presentation";
import { getEnquiry, getEnquiryWorkspace, getStaffDirectory } from "@/lib/crm/queries";

export default async function EnquiryPage({ params }: PageProps<"/dashboard/enquiries/[id]">) {
  const { id } = await params;
  const [profile, enquiry, workspace, staff] = await Promise.all([requireModuleAccess("enquiries"), getEnquiry(id), getEnquiryWorkspace(id), getStaffDirectory()]);
  if (!enquiry) notFound();
  const phoneHref = formatPhoneLink(enquiry.customer?.phone);
  const whatsappHref = formatWhatsAppLink(enquiry.customer?.whatsapp_number || enquiry.customer?.phone);
  return <div className="space-y-7"><Link href="/dashboard/enquiries" className="inline-flex min-h-11 items-center gap-2 text-sm text-stone"><ArrowLeft size={16} />Back to enquiries</Link><PageHeading title={enquiryReference(enquiry.enquiry_number)} description={enquiry.subject || enquiry.product?.name || "General enquiry"} action={<form action={markContactedAction}><input type="hidden" name="id" value={id} /><button className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Check size={16} />Mark contacted</button></form>} />
    <div className="flex flex-wrap items-center gap-2"><span className="rounded-sm border border-line bg-paper px-3 py-2 text-sm">{statusLabel(enquiry.status)}</span><span className={`rounded-sm border px-3 py-2 text-sm ${priorityClass(enquiry.priority)}`}>{priorityLabel(enquiry.priority)}</span>{phoneHref && <a href={phoneHref} className="inline-flex min-h-10 items-center gap-2 rounded-md border border-line bg-paper px-3 text-sm"><Phone size={15} />Call</a>}{whatsappHref && <a href={whatsappHref} target="_blank" rel="noreferrer" className="inline-flex min-h-10 items-center gap-2 rounded-md border border-line bg-paper px-3 text-sm"><Send size={15} />WhatsApp</a>}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1.5fr)_minmax(20rem,0.8fr)]"><div className="space-y-6"><section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Opportunity</h2><dl className="mt-5 grid gap-x-8 gap-y-5 sm:grid-cols-2"><div><dt className="text-xs text-stone">Customer</dt><dd className="mt-1 text-sm">{enquiry.customer ? <Link href={`/dashboard/customers/${enquiry.customer.id}`} className="font-medium text-brass-dark">{enquiry.customer.name}</Link> : "—"}</dd></div><div><dt className="text-xs text-stone">Product</dt><dd className="mt-1 text-sm">{enquiry.product?.name || "General enquiry"}</dd></div><div><dt className="text-xs text-stone">Source</dt><dd className="mt-1 text-sm">{enquiry.source || "—"}</dd></div><div><dt className="text-xs text-stone">Salesperson</dt><dd className="mt-1 text-sm">{enquiry.assigned?.full_name || "Unassigned"}</dd></div><div><dt className="text-xs text-stone">Created</dt><dd className="mt-1 text-sm">{formatDate(enquiry.created_at, true)}</dd></div><div><dt className="text-xs text-stone">Next follow-up</dt><dd className="mt-1 text-sm">{formatDate(enquiry.follow_up_at, true)}</dd></div></dl>{enquiry.message && <div className="mt-6 border-t border-line pt-5"><p className="text-xs text-stone">Customer requirement</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{enquiry.message}</p></div>}</section>
      <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Update enquiry</h2><div className="mt-5"><EnquiryEditor enquiry={enquiry} role={profile.role} /></div></section>
      <section><div className="flex items-center gap-2"><Clock3 size={18} /><h2 className="text-lg font-semibold">Follow-ups</h2></div><div className="mt-4 divide-y divide-line border-y border-line bg-paper sm:rounded-lg sm:border">{workspace.followUps.length ? workspace.followUps.map((task) => <div key={task.id} className="px-4 py-4"><div className="flex items-start justify-between gap-4"><div><p className="font-medium">{task.title}</p><p className="mt-1 text-xs text-stone">{task.assigned?.full_name || "Unassigned"} · {formatDate(task.due_at, true)}</p>{task.description && <p className="mt-2 text-sm text-stone">{task.description}</p>}</div><span className="text-xs text-stone">{followUpStatusLabel(task.status)}</span></div>{task.status !== "completed" && task.status !== "cancelled" && <div className="mt-3 flex flex-wrap items-end gap-3"><form action={completeFollowUpAction}><input type="hidden" name="id" value={task.id} /><input type="hidden" name="enquiry_id" value={id} /><button className="min-h-10 text-sm font-medium text-emerald-700">Complete</button></form><form action={cancelFollowUpAction}><input type="hidden" name="id" value={task.id} /><input type="hidden" name="enquiry_id" value={id} /><button className="min-h-10 text-sm font-medium text-red-700">Cancel</button></form><form action={rescheduleFollowUpAction} className="flex flex-wrap items-center gap-2"><input type="hidden" name="id" value={task.id} /><input type="hidden" name="enquiry_id" value={id} /><input className="min-h-10 rounded-md border border-line px-2 text-base" name="due_at" type="datetime-local" defaultValue={task.due_at ? new Date(new Date(task.due_at).getTime() + 14400000).toISOString().slice(0,16) : ""} required /><button className="min-h-10 text-sm font-medium text-brass-dark">Reschedule</button></form></div>}</div>) : <p className="px-4 py-8 text-center text-sm text-stone">No follow-ups yet.</p>}</div></section>
      <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Activity timeline</h2><ol className="mt-5 border-l border-line pl-6">{workspace.timeline.map((item) => <li key={item.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[1.72rem] top-1 size-2 rounded-full bg-brass" /><div className="flex flex-wrap items-baseline justify-between gap-2"><p className="text-sm font-semibold">{activityLabel(item.activity_type)}</p><time className="text-xs text-stone">{formatDate(item.occurred_at, true)}</time></div>{item.note && <p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-stone">{item.note}</p>}<p className="mt-1 text-xs text-stone">{item.actor?.full_name || "System / website"}</p></li>)}</ol></section></div>
      <aside className="space-y-5"><section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Assignment</h2>{profile.role === "admin" ? <form action={assignEnquiryAction} className="mt-4 space-y-3"><input type="hidden" name="id" value={id} /><select name="assigned_to" defaultValue={enquiry.assigned_to || ""} className="min-h-11 w-full rounded-md border border-line bg-paper px-3 text-base"><option value="">Unassigned</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select><button className="min-h-10 text-sm font-medium text-brass-dark">Save assignment</button></form> : <p className="mt-3 text-sm text-stone">{enquiry.assigned?.full_name || "Unassigned"}</p>}</section><section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Add follow-up</h2><div className="mt-4"><FollowUpForm enquiryId={id} customerId={enquiry.customer_id} staff={staff} role={profile.role} defaultAssignee={enquiry.assigned_to} currentUserId={profile.id} /></div></section><section className="rounded-lg border border-line bg-paper p-5"><EnquiryNoteForm enquiryId={id} /></section></aside></div>
  </div>;
}
