import Link from "next/link";
import { ArrowLeft, Download, FileCheck2, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { downloadPaymentProofAction } from "@/app/dashboard/payments/actions";
import { PaymentProofUploader, VoidReceiptForm } from "@/components/dashboard/payment-controls";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusNotice } from "@/components/ui/status-notice";
import { requireModuleAccess } from "@/lib/auth/dal";
import { formatDate } from "@/lib/crm/presentation";
import { formatMoney } from "@/lib/quotations/money";
import { paymentMethodLabel } from "@/lib/payments/presentation";
import { getReceipt } from "@/lib/payments/queries";

function bytes(value: number) { return value >= 1048576 ? `${(value / 1048576).toFixed(1)} MB` : `${Math.ceil(value / 1024)} KB`; }
export default async function ReceiptPage({ params }: PageProps<"/dashboard/payments/[id]">) {
  const { id } = await params;
  await requireModuleAccess("payments");
  const receipt = await getReceipt(id);
  if (!receipt) notFound();
  const currency = receipt.project?.currency || "AED";
  return <div className="mx-auto max-w-5xl space-y-7"><Link href={`/dashboard/payments/projects/${receipt.project_id}`} className="inline-flex min-h-11 items-center gap-2 text-sm text-stone"><ArrowLeft size={16} />Back to project payments</Link><PageHeading title={receipt.receipt_number} description={`${receipt.customer?.name || "Customer"} · ${receipt.project?.project_number || "Project"}`} action={<div className="flex flex-wrap items-center gap-2"><Link href={`/dashboard/payments/${receipt.id}/pdf`} target="_blank" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><ReceiptText size={16} />View receipt PDF</Link><span className={`rounded-sm border px-3 py-2 text-sm ${receipt.voided_at ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{receipt.voided_at ? "Void" : "Posted"}</span></div>} />
    {receipt.voided_at ? <StatusNotice tone="error" title="This receipt is void"><p>{receipt.void_reason} · voided {formatDate(receipt.voided_at, true)} by {receipt.voider?.full_name || "Finance team"}.</p></StatusNotice> : null}
    <div className="grid gap-6 lg:grid-cols-[minmax(0,1.4fr)_minmax(18rem,0.6fr)]"><div className="space-y-6"><section className={`overflow-hidden rounded-lg bg-graphite text-white ${receipt.voided_at ? "opacity-70" : ""}`}><div className="p-6"><p className="text-[10px] uppercase tracking-[0.18em] text-white/40">Amount received</p><p className={`mt-3 text-4xl font-semibold tracking-[-0.05em] ${receipt.voided_at ? "line-through" : ""}`}>{formatMoney(receipt.amount_received, currency)}</p><p className="mt-3 text-sm text-white/55">{receipt.milestone?.name || "Payment milestone"}</p></div><dl className="grid grid-cols-2 border-t border-white/10"><div className="border-r border-white/10 p-4"><dt className="text-[10px] uppercase tracking-[0.15em] text-white/35">Received</dt><dd className="mt-1 text-sm">{formatDate(receipt.received_date)}</dd></div><div className="p-4"><dt className="text-[10px] uppercase tracking-[0.15em] text-white/35">Method</dt><dd className="mt-1 text-sm">{paymentMethodLabel(receipt.payment_method)}</dd></div></dl></section>
      <section className="rounded-lg border border-line bg-paper p-5 sm:p-6"><h2 className="text-lg font-semibold">Receipt record</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs text-stone">Transaction reference</dt><dd className="mt-1 text-sm">{receipt.reference_number || "—"}</dd></div><div><dt className="text-xs text-stone">Posted by</dt><dd className="mt-1 text-sm">{receipt.creator?.full_name || "Finance team"}</dd></div><div><dt className="text-xs text-stone">Posted at</dt><dd className="mt-1 text-sm">{formatDate(receipt.created_at, true)}</dd></div><div><dt className="text-xs text-stone">Receipt number</dt><dd className="mt-1 text-sm font-medium">{receipt.receipt_number}</dd></div></dl>{receipt.notes ? <div className="mt-5 border-t border-line pt-4"><p className="text-xs text-stone">Internal note</p><p className="mt-2 whitespace-pre-wrap text-sm">{receipt.notes}</p></div> : null}</section>
      <section className="rounded-lg border border-line bg-paper p-5 sm:p-6"><h2 className="text-lg font-semibold">Payment proofs</h2><div className="mt-4 divide-y divide-line">{receipt.proofs.length ? receipt.proofs.map((proof) => <div key={proof.id} className="flex items-center justify-between gap-4 py-3 first:pt-0"><div className="min-w-0"><p className="truncate text-sm font-medium">{proof.file_name}</p><p className="text-xs text-stone">{bytes(proof.file_size)} · {formatDate(proof.created_at, true)}</p></div><form action={downloadPaymentProofAction}><input type="hidden" name="proof_id" value={proof.id} /><button className="grid size-11 place-items-center rounded-md border border-line" aria-label={`Download ${proof.file_name}`}><Download size={16} /></button></form></div>) : <p className="py-4 text-sm text-stone">No proof uploaded.</p>}</div>{!receipt.voided_at ? <div className="mt-5 border-t border-line pt-5"><PaymentProofUploader paymentId={receipt.id} /></div> : null}</section>
    </div><aside className="space-y-5"><section className="rounded-lg border border-line bg-paper p-5"><FileCheck2 size={19} className="text-brass-dark" /><h2 className="mt-4 text-base font-semibold">Immutable receipt</h2><p className="mt-2 text-sm leading-6 text-stone">Amount, project, milestone, date, method, and number cannot be edited after posting.</p></section>{!receipt.voided_at ? <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Reverse receipt</h2><p className="mt-2 text-sm leading-6 text-stone">Voiding excludes this amount from every total while preserving the audit trail.</p><div className="mt-5"><VoidReceiptForm paymentId={receipt.id} projectId={receipt.project_id} /></div></section> : null}</aside></div>
  </div>;
}
