import Link from "next/link";
import { ArrowUpRight, BarChart3, CalendarDays, CircleDollarSign, FolderKanban, MessageSquareText } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";
import { requireModuleAccess } from "@/lib/auth/dal";
import { formatDate } from "@/lib/crm/presentation";
import { formatMoney } from "@/lib/quotations/money";
import { getManagementReport } from "@/lib/reports/queries";
import { resolveReportRange } from "@/lib/reports/ranges";

function Metric({ label, value, detail }: { label:string; value:string|number; detail?:string }) {
  return <article className="min-w-0 border-l border-white/15 px-4 first:border-l-0"><p className="text-[10px] uppercase tracking-[0.15em] text-white/45">{label}</p><strong className="mt-2 block truncate text-2xl tracking-[-0.04em] text-white">{value}</strong>{detail ? <p className="mt-1 text-xs text-white/45">{detail}</p> : null}</article>;
}

function MiniBars({ rows, money=false }: { rows:[string,number][]; money?:boolean }) {
  const max = Math.max(...rows.map((row)=>row[1]), 1);
  return <div className="space-y-3">{rows.length ? rows.map(([label,value])=><div key={label} className="grid grid-cols-[minmax(5.5rem,0.8fr)_minmax(4rem,1.4fr)_auto] items-center gap-3 text-xs"><span className="truncate text-stone">{label.replaceAll("_"," ")}</span><span className="h-1.5 overflow-hidden rounded-full bg-limestone"><span className="block h-full rounded-full bg-brass-dark" style={{width:`${Math.max((value/max)*100,value?4:0)}%`}} /></span><strong className="min-w-8 text-right">{money?formatMoney(value):value}</strong></div>) : <p className="text-sm text-stone">No activity in this period.</p>}</div>;
}

function Conversion({ title, numerator, denominator, rate, note }: { title:string;numerator:number;denominator:number;rate:number|null;note:string }) {
  return <article className="rounded-lg border border-line bg-paper p-4"><div className="flex items-baseline justify-between gap-3"><h3 className="text-sm font-semibold">{title}</h3><strong className="text-2xl tracking-[-0.04em]">{rate===null?"—":`${rate}%`}</strong></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-limestone"><div className="h-full bg-brass-dark" style={{width:`${rate||0}%`}} /></div><p className="mt-3 text-xs text-stone">{numerator} of {denominator} · {note}</p></article>;
}

const presets = [["today","Today"],["7d","Last 7 days"],["month","This month"],["last_month","Last month"],["quarter","This quarter"],["custom","Custom"]];

export default async function ReportsPage({ searchParams }: PageProps<"/dashboard/reports">) {
  const [profile, params] = await Promise.all([requireModuleAccess("reports"), searchParams]);
  const range = resolveReportRange(params);
  const report = await getManagementReport(range, profile.role);
  const projectValue = report.projects.delayedRows as unknown as {id:string;project_number:string;expected_completion_date:string|null;project_value:number;currency:string;customer:{id:string;name:string}|null;current_stage:{name:string}|null}[];
  return <div className="space-y-8">
    <PageHeading title="Management reports" description="Operational performance from enquiry through completion, collections, and customer feedback." />
    <section className="rounded-lg border border-line bg-paper p-4">
      <div className="flex gap-2 overflow-x-auto pb-2">{presets.map(([key,label])=><Link key={key} href={`/dashboard/reports?range=${key}`} className={`shrink-0 rounded-full border px-4 py-2 text-sm ${range.preset===key?"border-graphite bg-graphite text-white":"border-line bg-paper"}`}>{label}</Link>)}</div>
      {range.preset==="custom" ? <form className="mt-3 grid gap-3 border-t border-line pt-4 sm:grid-cols-[1fr_1fr_auto]"><input type="hidden" name="range" value="custom" /><label className="grid gap-1 text-xs font-medium">From<input type="date" name="from" defaultValue={range.from} className="min-h-11 rounded-md border border-line px-3 text-base" /></label><label className="grid gap-1 text-xs font-medium">To<input type="date" name="to" defaultValue={range.to} className="min-h-11 rounded-md border border-line px-3 text-base" /></label><button className="min-h-11 self-end rounded-md bg-graphite px-4 text-sm font-semibold text-white">Apply range</button></form> : null}
      <p className="mt-3 flex items-center gap-2 text-xs text-stone"><CalendarDays size={14} />{formatDate(range.from)} to {formatDate(range.to)} · Dubai business dates</p>
    </section>
    <section className="overflow-hidden rounded-lg bg-graphite"><div className="grid gap-y-6 px-2 py-5 sm:grid-cols-2 lg:grid-cols-4">
      <Metric label="Enquiries" value={report.crm.total} detail={`${report.crm.newCount} currently new`} />
      <Metric label="Approved value" value={formatMoney(report.finance.approvedValue)} detail="Approved quotations in range" />
      <Metric label="Collected" value={formatMoney(report.finance.received)} detail="Valid receipts in range" />
      <Metric label="Outstanding" value={formatMoney(report.finance.outstanding)} detail={`${formatMoney(report.finance.overdue)} overdue`} />
    </div></section>
    <section><div className="flex items-center gap-2"><BarChart3 size={18} className="text-brass-dark" /><h2 className="text-lg font-semibold">Conversion</h2></div><p className="mt-1 text-sm text-stone">Each rate uses records created in the selected period; current downstream links determine conversion.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Conversion title="Enquiry → site visit" {...report.conversion.enquiryToVisit} note="enquiries with ≥1 linked visit / eligible enquiries" />
      <Conversion title="Site visit → quotation" {...report.conversion.visitToQuote} note="visits with ≥1 linked quotation / eligible visits" />
      <Conversion title="Quotation → approved" {...report.conversion.quoteApproval} note="currently approved / customer-facing sent, approved, or rejected" />
      <Conversion title="Approved → project" {...report.conversion.approvedToProject} note="approved quotations linked to a project / approved quotations" />
    </div></section>
    <section className="overflow-hidden rounded-lg border border-line bg-paper"><div className="border-b border-line px-5 py-4"><h2 className="text-base font-semibold">Lead source performance</h2><p className="mt-1 text-xs text-stone">Qualified: contacted, follow-up, site visit required, quotation, or approved. Converted / won: approved or linked to a project. Project value: linked project value.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-limestone text-xs text-stone"><tr><th className="px-5 py-3 font-medium">Source</th><th className="px-4 py-3 font-medium">Enquiries</th><th className="px-4 py-3 font-medium">Qualified</th><th className="px-4 py-3 font-medium">Converted / won</th><th className="px-4 py-3 font-medium">Conversion</th><th className="px-5 py-3 text-right font-medium">Project value</th></tr></thead><tbody className="divide-y divide-line">{report.crm.sourcePerformance.map(row=><tr key={row.source}><td className="px-5 py-3 font-medium">{row.source}</td><td className="px-4 py-3">{row.enquiries}</td><td className="px-4 py-3">{row.qualified}</td><td className="px-4 py-3">{row.converted}</td><td className="px-4 py-3">{row.conversion===null?"—":`${row.conversion}%`}</td><td className="px-5 py-3 text-right">{formatMoney(row.projectValue)}</td></tr>)}{!report.crm.sourcePerformance.length&&<tr><td colSpan={6} className="px-5 py-8 text-center text-stone">No lead sources in this period.</td></tr>}</tbody></table></div></section>
    <div className="grid gap-5 xl:grid-cols-2">
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Lead sources</h2><p className="mt-1 text-xs text-stone">Enquiries created in range.</p><div className="mt-5"><MiniBars rows={report.crm.bySource} /></div></section>
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Enquiry trend</h2><p className="mt-1 text-xs text-stone">Daily volume in range.</p><div className="mt-5"><MiniBars rows={report.crm.trend} /></div></section>
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Pipeline status</h2><p className="mt-1 text-xs text-stone">Current status of enquiries created in range.</p><div className="mt-5"><MiniBars rows={report.crm.byStatus} /></div></section>
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Salesperson enquiry summary</h2><div className="mt-4 divide-y divide-line">{report.crm.salesperson.map((row)=><div key={row.name} className="grid grid-cols-[1fr_auto_auto] gap-4 py-3 text-sm"><span className="truncate">{row.name}</span><span>{row.total} total</span><span className="text-stone">{row.newCount} new</span></div>)}</div><p className="mt-3 border-t border-line pt-3 text-xs text-stone">Follow-ups: {report.crm.dueFollowUps} due today · <strong className={report.crm.overdueFollowUps?"text-red-700":""}>{report.crm.overdueFollowUps} overdue</strong></p></section>
    </div>
    <section><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><FolderKanban size={18} className="text-brass-dark" /><h2 className="text-lg font-semibold">Project delivery</h2></div><Link href="/dashboard/projects" className="text-sm font-semibold text-brass-dark">Open projects</Link></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-5">{[["Active",report.projects.active],["Completed in range",report.projects.completed],["Delayed",report.projects.delayed],["Installations · 7 days",report.projects.upcomingInstallations],["Pending handovers",report.projects.pendingHandovers]].map(([label,value])=><article key={String(label)} className="rounded-lg border border-line bg-paper p-4"><strong className={`text-2xl ${label==="Delayed"&&Number(value)>0?"text-red-700":""}`}>{value}</strong><p className="mt-3 text-xs text-stone">{label}</p></article>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[0.7fr_1.3fr]"><div className="rounded-lg border border-line bg-paper p-5"><h3 className="font-semibold">Active stages</h3><div className="mt-5"><MiniBars rows={report.projects.byStage} /></div></div><div className="overflow-hidden rounded-lg border border-line bg-paper"><div className="border-b border-line px-5 py-4"><h3 className="font-semibold">Delayed projects</h3></div><div className="divide-y divide-line">{projectValue.length?projectValue.map((project)=><Link key={project.id} href={`/dashboard/projects/${project.id}`} className="grid gap-1 px-5 py-4 sm:grid-cols-[8rem_minmax(0,1fr)_8rem_auto] sm:items-center"><strong className="text-sm text-brass-dark">{project.project_number}</strong><span className="truncate text-sm">{project.customer?.name||"Customer"}</span><span className="text-xs text-stone">{project.current_stage?.name||"Unstaged"}</span><span className="text-xs text-red-700">due {formatDate(project.expected_completion_date)}</span></Link>):<p className="px-5 py-8 text-center text-sm text-stone">No delayed projects.</p>}</div></div></div></section>
    <section><div className="flex items-center gap-2"><CircleDollarSign size={18} className="text-brass-dark" /><h2 className="text-lg font-semibold">Finance position</h2></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{[["Portfolio value",report.finance.projectValue],["Outstanding",report.finance.outstanding],["Overdue",report.finance.overdue],["Due next 7 days",report.finance.dueNext7]].map(([label,value])=><article key={String(label)} className="rounded-lg border border-line bg-paper p-4"><strong className={`block truncate text-xl ${label==="Overdue"&&Number(value)>0?"text-red-700":""}`}>{formatMoney(Number(value))}</strong><p className="mt-3 text-xs text-stone">{label}</p></article>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-lg border border-line bg-paper p-5"><h3 className="font-semibold">Collections trend</h3><p className="mt-1 text-xs text-stone">Valid receipts by received date.</p><div className="mt-5"><MiniBars rows={report.finance.collectionTrend} money /></div></div><div className="overflow-hidden rounded-lg border border-line bg-paper"><div className="border-b border-line px-5 py-4"><h3 className="font-semibold">Largest outstanding projects</h3></div><div className="divide-y divide-line">{report.finance.outstandingProjects.map((row)=><Link key={row.project_id} href={`/dashboard/payments/projects/${row.project_id}`} className="grid grid-cols-[1fr_auto] gap-3 px-5 py-4"><span className="min-w-0"><strong className="block truncate text-sm">{row.project_number}</strong><span className="block truncate text-xs text-stone">{row.customer_name}</span></span><strong className="text-sm">{formatMoney(Number(row.outstanding),row.currency)}</strong></Link>)}</div></div></div></section>
    <section><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><MessageSquareText size={18} className="text-brass-dark" /><h2 className="text-lg font-semibold">Customer satisfaction</h2></div><Link href="/dashboard/feedback" className="text-sm font-semibold text-brass-dark">Open feedback</Link></div><div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4"><article className="rounded-lg border border-line bg-paper p-4"><strong className="text-2xl">{report.customer.completedProjects}</strong><p className="mt-3 text-xs text-stone">Completed projects in range</p></article><article className="rounded-lg border border-line bg-paper p-4"><strong className="text-2xl">{report.customer.feedbackReceived}</strong><p className="mt-3 text-xs text-stone">Feedback received in range</p></article><article className="rounded-lg border border-line bg-paper p-4"><strong className="text-2xl">{report.customer.averageRating??"—"}</strong><p className="mt-3 text-xs text-stone">Average rating / 5</p></article><article className="rounded-lg border border-line bg-paper p-4"><strong className={report.customer.awaitingReview?"text-2xl text-amber-800":"text-2xl"}>{report.customer.awaitingReview}</strong><p className="mt-3 text-xs text-stone">Awaiting review</p></article></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><div className="rounded-lg border border-line bg-paper p-5"><h3 className="font-semibold">Rating distribution</h3><div className="mt-5"><MiniBars rows={report.customer.distribution} /></div></div><div className="rounded-lg border border-line bg-paper p-5"><h3 className="font-semibold">Feedback requiring review</h3><div className="mt-3 divide-y divide-line">{report.customer.reviewRows.length?report.customer.reviewRows.map((item)=><Link key={item.id} href="/dashboard/feedback?status=received" className="flex items-center justify-between gap-3 py-3 text-sm"><span className="truncate">{item.project?.project_number||"Project"} · {item.project?.customer?.name||"Customer"}</span><span className="inline-flex items-center gap-1 font-semibold text-brass-dark">{item.rating}/5 <ArrowUpRight size={13} /></span></Link>):<p className="py-6 text-center text-sm text-stone">No feedback awaiting review.</p>}</div></div></div></section>
    <p className="border-t border-line pt-4 text-xs leading-5 text-stone">Report definitions: period activity uses Dubai dates. Active project, outstanding, overdue, follow-up, handover, and installation figures are current operational positions; approved quotation value and collections are period flows. Voided and archived receipts are excluded.</p>
  </div>;
}
