import Link from "next/link";
import { ArrowLeft, Ban, Download, FileCheck2, Landmark, ReceiptText } from "lucide-react";
import { notFound } from "next/navigation";
import { transitionInvoiceAction } from "@/app/dashboard/invoices/actions";
import { InvoiceBuilder } from "@/components/dashboard/invoice-builder";
import { PageHeading } from "@/components/ui/page-heading";
import { StatusNotice } from "@/components/ui/status-notice";
import { requireModuleAccess } from "@/lib/auth/dal";
import { formatDate } from "@/lib/crm/presentation";
import { invoiceActivityLabel, invoiceStatusClass, invoiceStatusLabel } from "@/lib/invoices/presentation";
import { getInvoice, getInvoiceWorkspace } from "@/lib/invoices/queries";
import { formatMoney } from "@/lib/quotations/money";

function Detail({ label, value }: { label: string; value?: React.ReactNode }) {
  return <div><dt className="text-xs text-stone">{label}</dt><dd className="mt-1 text-sm leading-6">{value || "—"}</dd></div>;
}

export default async function InvoicePage({ params, searchParams }: PageProps<"/dashboard/invoices/[id]">) {
  const [{ id }, query] = await Promise.all([params, searchParams]);
  await requireModuleAccess("invoices");
  const invoice = await getInvoice(id);
  if (!invoice) notFound();
  const workspace = await getInvoiceWorkspace(invoice);
  const remaining = Math.max(0, invoice.total - workspace.received);
  const notice = typeof query.status === "string" ? query.status : typeof query.error === "string" ? "error" : typeof query.created === "string" ? "created" : "";
  return <div className="mx-auto max-w-[94rem] space-y-7">
    <Link href="/dashboard/invoices" className="inline-flex min-h-11 items-center gap-2 text-sm text-stone"><ArrowLeft size={16} />Back to invoices</Link>
    <PageHeading title={invoice.invoice_number} description={`${invoice.customer_name_snapshot} · ${invoice.project?.project_number || "Project"}`} action={<div className="flex flex-wrap items-center gap-2"><Link href={`/dashboard/invoices/${invoice.id}/pdf`} target="_blank" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Download size={16} />View invoice PDF</Link><span className={`rounded-sm border px-3 py-2 text-sm ${invoiceStatusClass(invoice.status)}`}>{invoiceStatusLabel(invoice.status)}</span></div>} />
    {notice === "created" ? <StatusNotice tone="success" title="Draft invoice created"><p>Review the copied quotation snapshot, adjust it if needed, then issue it.</p></StatusNotice> : null}
    {notice === "issued" ? <StatusNotice tone="success" title="Invoice issued"><p>The commercial snapshot is now locked.</p></StatusNotice> : null}
    {notice === "cancelled" ? <StatusNotice tone="error" title="Invoice cancelled"><p>The record remains available for audit and cannot be reopened.</p></StatusNotice> : null}
    {notice === "error" ? <StatusNotice tone="error" title="Invoice action failed"><p>{decodeURIComponent(String(query.error))}</p></StatusNotice> : null}

    <section className="overflow-hidden rounded-lg bg-graphite text-white">
      <div className="grid gap-6 p-6 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-end">
        <div><p className="text-xs font-medium text-brass">Client / job reference</p><p className="mt-2 break-all text-xl font-semibold tracking-[-0.03em] sm:text-2xl">{invoice.client_reference}</p><p className="mt-2 text-sm text-white/55">{invoice.site_address_snapshot || "Site not specified"}</p></div>
        <p className="text-3xl font-semibold tracking-[-0.04em]">{formatMoney(invoice.total, invoice.currency)}</p>
      </div>
      <dl className="grid grid-cols-2 border-t border-white/10 lg:grid-cols-4"><div className="border-r border-white/10 p-4"><dt className="text-xs text-white/45">Issue date</dt><dd className="mt-1 text-sm">{formatDate(invoice.issue_date)}</dd></div><div className="border-r border-white/10 p-4"><dt className="text-xs text-white/45">Due date</dt><dd className="mt-1 text-sm">{formatDate(invoice.due_date)}</dd></div><div className="border-r border-white/10 p-4"><dt className="text-xs text-white/45">Approved quotation</dt><dd className="mt-1 text-sm">{invoice.quotation_number_snapshot || "—"}</dd></div><div className="p-4"><dt className="text-xs text-white/45">Revision</dt><dd className="mt-1 text-sm">{invoice.quotation_revision_snapshot ?? "—"}</dd></div></dl>
    </section>

    {invoice.status === "draft" ? <>
      <InvoiceBuilder invoice={invoice} items={workspace.items} />
      <section className="grid gap-5 rounded-lg border border-line bg-paper p-5 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div><FileCheck2 size={19} className="text-brass-dark" /><h2 className="mt-3 text-lg font-semibold">Issue this invoice</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-stone">Issuing locks dates, customer/site snapshots, items, prices, discount, VAT, notes, and terms. Future product-price changes will not affect it.</p></div><form action={transitionInvoiceAction}><input type="hidden" name="id" value={invoice.id} /><input type="hidden" name="action" value="issue" /><button className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-md bg-brass px-5 text-sm font-semibold text-ink"><FileCheck2 size={16} />Issue invoice</button></form></section>
    </> : <div className="grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(20rem,0.55fr)]"><div className="space-y-6">
      <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-semibold">Issued commercial snapshot</h2><p className="mt-1 text-sm text-stone">Values below are preserved from the invoice at issue.</p></div></div><div className="mt-5 hidden overflow-x-auto md:block"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-y border-line bg-limestone/70 text-xs text-stone"><tr><th className="px-3 py-3 font-medium">Description</th><th className="px-3 py-3 text-right font-medium">Qty</th><th className="px-3 py-3 font-medium">Unit</th><th className="px-3 py-3 text-right font-medium">Unit price</th><th className="px-3 py-3 text-right font-medium">Amount</th></tr></thead><tbody className="divide-y divide-line">{workspace.items.map((item) => <tr key={item.id}><td className="px-3 py-3"><p className="font-medium">{item.item_name}</p>{item.description ? <p className="mt-1 text-xs text-stone">{item.description}</p> : null}</td><td className="px-3 py-3 text-right">{item.quantity}</td><td className="px-3 py-3">{item.unit}</td><td className="px-3 py-3 text-right">{formatMoney(item.unit_price, invoice.currency)}</td><td className="px-3 py-3 text-right font-semibold">{formatMoney(item.line_total, invoice.currency)}</td></tr>)}</tbody></table></div><div className="mt-5 divide-y divide-line md:hidden">{workspace.items.map((item) => <div key={item.id} className="py-4 first:pt-0"><div className="flex justify-between gap-4"><strong className="text-sm">{item.item_name}</strong><strong className="text-sm">{formatMoney(item.line_total, invoice.currency)}</strong></div><p className="mt-1 text-xs text-stone">{item.quantity} {item.unit} × {formatMoney(item.unit_price, invoice.currency)}{item.taxable ? " · Taxable" : ""}</p>{item.description ? <p className="mt-2 text-sm text-stone">{item.description}</p> : null}</div>)}</div><dl className="ml-auto mt-5 max-w-sm space-y-2 border-t border-line pt-4 text-sm"><div className="flex justify-between"><dt className="text-stone">Subtotal</dt><dd>{formatMoney(invoice.subtotal, invoice.currency)}</dd></div><div className="flex justify-between"><dt className="text-stone">Discount</dt><dd>-{formatMoney(invoice.discount_amount, invoice.currency)}</dd></div><div className="flex justify-between"><dt className="text-stone">VAT ({invoice.vat_rate}%)</dt><dd>{formatMoney(invoice.vat_amount, invoice.currency)}</dd></div><div className="flex justify-between border-t border-line pt-3 text-base font-semibold"><dt>Total</dt><dd>{formatMoney(invoice.total, invoice.currency)}</dd></div></dl></section>
      <section className="rounded-lg border border-line bg-paper p-5 sm:p-6"><h2 className="text-lg font-semibold">Customer and terms</h2><dl className="mt-5 grid gap-5 sm:grid-cols-2"><Detail label="Customer" value={invoice.customer_name_snapshot} /><Detail label="Company" value={invoice.customer_company_snapshot} /><Detail label="Phone" value={invoice.customer_phone_snapshot} /><Detail label="Email" value={invoice.customer_email_snapshot} /><Detail label="Site / project" value={invoice.site_address_snapshot} /><Detail label="Created by" value={invoice.creator?.full_name} /></dl>{invoice.notes ? <div className="mt-5 border-t border-line pt-4"><p className="text-xs text-stone">Notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{invoice.notes}</p></div> : null}{invoice.terms ? <div className="mt-5 border-t border-line pt-4"><p className="text-xs text-stone">Terms</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{invoice.terms}</p></div> : null}</section>
    </div><aside className="space-y-5"><section className="rounded-lg border border-line bg-paper p-5"><Landmark size={19} className="text-brass-dark" /><h2 className="mt-4 text-base font-semibold">Payment position</h2>{workspace.paymentRelationshipValid ? <dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt className="text-stone">Invoice total</dt><dd>{formatMoney(invoice.total, invoice.currency)}</dd></div><div className="flex justify-between"><dt className="text-stone">Received on project</dt><dd>{formatMoney(workspace.received, invoice.currency)}</dd></div><div className="flex justify-between border-t border-line pt-3 font-semibold"><dt>Remaining</dt><dd>{formatMoney(remaining, invoice.currency)}</dd></div></dl> : <p className="mt-3 text-sm leading-6 text-stone">Project receipts remain authoritative. A received/remaining allocation is shown only when exactly one active issued invoice exists for the project.</p>}<Link href={`/dashboard/payments/projects/${invoice.project_id}`} className="mt-5 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-brass-dark"><ReceiptText size={15} />Open project payments</Link></section>
      {invoice.status !== "cancelled" ? <section className="rounded-lg border border-line bg-paper p-5"><Ban size={18} className="text-red-700" /><h2 className="mt-3 text-base font-semibold">Cancel invoice</h2><p className="mt-2 text-sm leading-6 text-stone">Cancellation preserves the invoice and activity trail.</p><form action={transitionInvoiceAction} className="mt-4 space-y-3"><input type="hidden" name="id" value={invoice.id} /><input type="hidden" name="action" value="cancel" /><textarea name="reason" required minLength={3} placeholder="Reason for cancellation" className="min-h-24 w-full rounded-md border border-line bg-paper px-3 py-2 text-base" /><button className="min-h-11 w-full rounded-md border border-red-200 text-sm font-semibold text-red-700">Cancel invoice</button></form></section> : null}
      <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-base font-semibold">Invoice activity</h2><ol className="mt-5 border-l border-line pl-5">{workspace.timeline.length ? workspace.timeline.map((item) => <li key={item.id} className="relative pb-5 last:pb-0"><span className="absolute -left-[1.43rem] top-1 size-2 rounded-full bg-brass" /><p className="text-sm font-medium">{invoiceActivityLabel(item.event_type)}</p><p className="mt-1 text-xs text-stone">{item.actor?.full_name || "System"} · {formatDate(item.created_at, true)}</p></li>) : <li className="text-sm text-stone">No activity recorded.</li>}</ol></section>
    </aside></div>}
  </div>;
}
