"use client";

import { useActionState, useMemo, useState } from "react";
import { createEnquiryAction } from "@/app/dashboard/enquiries/actions";
import { ENQUIRY_SOURCES, LEAD_PRIORITIES, PRIORITY_LABELS } from "@/lib/crm/constants";
import { INITIAL_CRM_ACTION_STATE, type StaffSummary } from "@/lib/crm/types";
import type { AppRole } from "@/lib/auth/permissions";

type CustomerOption = { id: string; name: string; phone: string | null; whatsapp_number: string | null; email: string | null; company_name: string | null };
type ProductOption = { id: string; name: string; product_code: string | null };
const input = "min-h-12 w-full rounded-md border border-line bg-paper px-3 text-base";
const label = "grid gap-2 text-sm font-medium";
function ErrorLine({ messages }: { messages?: string[] }) { return messages?.[0] ? <span className="font-normal text-red-700">{messages[0]}</span> : null; }

export function EnquiryForm({ customers, products, staff, role, currentUserId, initialCustomerId = "" }: { customers: CustomerOption[]; products: ProductOption[]; staff: StaffSummary[]; role: AppRole; currentUserId: string; initialCustomerId?: string }) {
  const [state, action, pending] = useActionState(createEnquiryAction, INITIAL_CRM_ACTION_STATE);
  const [mode, setMode] = useState<"existing" | "new">(customers.length ? "existing" : "new");
  const [search, setSearch] = useState("");
  const matches = useMemo(() => customers.filter((customer) => `${customer.name} ${customer.phone || ""} ${customer.company_name || ""}`.toLowerCase().includes(search.toLowerCase())).slice(0, 50), [customers, search]);
  return <form action={action} className="space-y-6">
    {state.message && <p role={state.status === "error" ? "alert" : "status"} className={`rounded-md border px-4 py-3 text-sm ${state.status === "error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{state.message}</p>}
    {state.duplicates?.length ? <div className="border-l-2 border-brass bg-paper px-4 py-4"><p className="text-sm font-semibold">Possible customer matches</p><p className="mt-1 text-sm text-stone">Link this enquiry to the right customer, or create a separate record.</p><div className="mt-3 flex flex-wrap gap-2">{state.duplicates.map((item) => <button key={item.id} name="matched_customer_id" value={item.id} className="min-h-11 rounded-md border border-line px-3 text-left text-sm"><strong>{item.name}</strong><span className="ml-2 text-stone">{item.phone || item.email}</span></button>)}<button name="allow_duplicate" value="true" className="min-h-11 rounded-md px-3 text-sm font-medium text-red-700">Create separate customer</button></div></div> : null}
    <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold tracking-[-0.025em]">Customer</h2><p className="mt-1 text-sm text-stone">Link an existing record or add the caller inline.</p></div><div className="flex rounded-md border border-line p-1 text-sm"><button type="button" onClick={() => setMode("existing")} className={`min-h-10 rounded px-3 ${mode === "existing" ? "bg-graphite text-white" : "text-stone"}`}>Existing</button><button type="button" onClick={() => setMode("new")} className={`min-h-10 rounded px-3 ${mode === "new" ? "bg-graphite text-white" : "text-stone"}`}>New</button></div></div>
      {mode === "existing" ? <div className="mt-5 grid gap-4"><label className={label}>Search customers<input className={input} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, phone, or company" /></label><label className={label}>Customer<select className={input} name="customer_id" required defaultValue={initialCustomerId}><option value="">Choose a customer</option>{matches.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}{customer.company_name ? ` — ${customer.company_name}` : ""}{customer.phone ? ` — ${customer.phone}` : ""}</option>)}</select></label><input type="hidden" name="customer_name" value="" /><input type="hidden" name="phone" value="" /><input type="hidden" name="whatsapp_number" value="" /><input type="hidden" name="email" value="" /><input type="hidden" name="company_name" value="" /><input type="hidden" name="customer_type" value="individual" /><input type="hidden" name="address" value="" /><input type="hidden" name="area" value="" /><input type="hidden" name="emirate" value="" /></div> : <div className="mt-5 grid gap-5 sm:grid-cols-2"><input type="hidden" name="customer_id" value="" /><label className={`${label} sm:col-span-2`}>Customer name<input className={input} name="customer_name" required maxLength={160} /><ErrorLine messages={state.fieldErrors?.customer_name} /></label><label className={label}>Type<select className={input} name="customer_type" defaultValue="individual"><option value="individual">Individual</option><option value="company">Company</option></select></label><label className={label}>Company<input className={input} name="company_name" maxLength={160} /></label><label className={label}>Phone<input className={input} name="phone" type="tel" maxLength={40} placeholder="+971 …" /><ErrorLine messages={state.fieldErrors?.phone} /></label><label className={label}>WhatsApp<input className={input} name="whatsapp_number" type="tel" maxLength={40} placeholder="+971 …" /></label><label className={label}>Email<input className={input} name="email" type="email" maxLength={254} /></label><label className={label}>Area<input className={input} name="area" maxLength={120} /></label><label className={label}>Emirate<input className={input} name="emirate" maxLength={80} /></label><label className={`${label} sm:col-span-2`}>Address<textarea className={`${input} min-h-20 py-3`} name="address" maxLength={500} /></label></div>}
    </section>
    <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold tracking-[-0.025em]">Enquiry</h2><div className="mt-5 grid gap-5 sm:grid-cols-2">
      <label className={label}>Source<select className={input} name="source" defaultValue="Phone">{ENQUIRY_SOURCES.filter((source) => source !== "Website").map((source) => <option key={source}>{source}</option>)}</select></label>
      <label className={label}>Product <span className="font-normal text-stone">optional</span><select className={input} name="product_id" defaultValue=""><option value="">No linked product</option>{products.map((product) => <option key={product.id} value={product.id}>{product.name}{product.product_code ? ` — ${product.product_code}` : ""}</option>)}</select></label>
      <label className={`${label} sm:col-span-2`}>Subject<input className={input} name="subject" maxLength={200} placeholder="Short description of the opportunity" /></label>
      <label className={`${label} sm:col-span-2`}>Requirement<textarea className={`${input} min-h-32 py-3`} name="message" required maxLength={6000} /><ErrorLine messages={state.fieldErrors?.message} /></label>
      <label className={label}>Priority<select className={input} name="priority" defaultValue="normal">{LEAD_PRIORITIES.map((priority) => <option key={priority} value={priority}>{PRIORITY_LABELS[priority]}</option>)}</select></label>
      <label className={label}>Assigned salesperson<select className={input} name="assigned_to" defaultValue={role === "sales" ? currentUserId : ""} disabled={role === "sales"}><option value="">Unassigned</option>{staff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select>{role === "sales" && <input type="hidden" name="assigned_to" value={currentUserId} />}</label>
      <label className={label}>First follow-up <span className="font-normal text-stone">optional</span><input className={input} name="follow_up_at" type="datetime-local" /></label>
      <label className={label}>Next action<input className={input} name="next_action" maxLength={300} placeholder="Call to confirm measurements" /></label>
      <label className={`${label} sm:col-span-2`}>Internal notes<textarea className={`${input} min-h-24 py-3`} name="internal_notes" maxLength={6000} /></label>
    </div></section>
    <div className="sticky bottom-16 z-10 flex justify-end border border-line bg-paper/95 px-4 py-3 shadow-lg backdrop-blur sm:rounded-lg lg:bottom-4"><button disabled={pending} className="min-h-12 rounded-md bg-graphite px-6 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Creating…" : "Create enquiry"}</button></div>
  </form>;
}
