"use client";

import Image from "next/image";
import { useActionState } from "react";
import { removeProductImageAction, setPrimaryProductImageAction, updateProductImageAction, uploadProductImageAction } from "@/app/dashboard/products/actions";
import type { ProductImage } from "@/lib/catalogue/types";
import { INITIAL_ACTION_STATE } from "@/lib/forms/action-state";

export function ProductMedia({ productId, images }: { productId: string; images: ProductImage[] }) {
  const [state, action, pending] = useActionState(uploadProductImageAction.bind(null, productId), INITIAL_ACTION_STATE);
  return <section className="rounded-lg border border-line bg-paper p-5 sm:p-6"><h2 className="text-lg font-semibold tracking-[-0.025em]">Product media</h2><p className="mt-1 text-sm text-stone">The cover image appears first. New unique paths prevent stale replacements.</p>
    <form action={action} className="mt-5 grid gap-4 lg:grid-cols-[1fr_1fr_auto] lg:items-end"><label className="grid gap-2 text-sm font-medium">Image<input name="image" type="file" accept="image/jpeg,image/png,image/webp" required className="min-h-12 rounded-md border border-line bg-limestone px-3 py-2 text-sm" /></label><label className="grid gap-2 text-sm font-medium">Alt text<input name="alt_text" maxLength={180} className="min-h-12 rounded-md border border-line bg-paper px-3 text-base" /></label><div className="flex min-h-12 items-center gap-3"><label className="flex items-center gap-2 text-sm"><input name="is_primary" type="checkbox" className="size-5 accent-brass-dark" />Make cover</label><button disabled={pending} className="min-h-12 rounded-md bg-graphite px-5 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Uploading…" : "Upload image"}</button></div></form>
    {state.message && <p className={`mt-3 text-sm ${state.status === "error" ? "text-red-700" : "text-emerald-700"}`}>{state.message}</p>}
    {images.length === 0 ? <div className="mt-6 rounded-md border border-dashed border-line bg-limestone px-5 py-10 text-center text-sm text-stone">No product images yet. Upload the cover image first.</div> : <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{images.map((image) => <article key={image.id} className="overflow-hidden rounded-md border border-line"><div className="relative aspect-[4/3] bg-limestone">{image.url ? <Image src={image.url} alt={image.alt_text || "Product image"} fill sizes="(max-width: 640px) 100vw, 320px" className="object-cover" /> : <div className="grid size-full place-items-center text-sm text-stone">Preview unavailable</div>}{image.is_primary && <span className="absolute left-3 top-3 rounded-sm bg-ink px-2 py-1 text-xs font-medium text-white">Cover</span>}</div><form action={updateProductImageAction} className="space-y-3 p-3"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="product_id" value={productId} /><label className="grid gap-1 text-xs font-medium text-stone">Alt text<input name="alt_text" defaultValue={image.alt_text || ""} maxLength={180} className="min-h-11 rounded-md border border-line px-3 text-base text-graphite" /></label><label className="grid gap-1 text-xs font-medium text-stone">Order<input name="sort_order" type="number" defaultValue={image.sort_order} min={-10000} max={10000} className="min-h-11 rounded-md border border-line px-3 text-base text-graphite" /></label><button className="min-h-10 text-sm font-medium text-brass-dark">Save image details</button></form><div className="flex border-t border-line px-3 py-2">{!image.is_primary && <form action={setPrimaryProductImageAction}><input type="hidden" name="id" value={image.id} /><input type="hidden" name="product_id" value={productId} /><button className="min-h-10 pr-4 text-sm font-medium">Set as cover</button></form>}<form action={removeProductImageAction} className="ml-auto"><input type="hidden" name="id" value={image.id} /><input type="hidden" name="product_id" value={productId} /><button className="min-h-10 text-sm font-medium text-red-700">Remove</button></form></div></article>)}</div>}
  </section>;
}
