"use client";

import { useActionState, useMemo, useState } from "react";
import { createSiteVisitAction } from "@/app/dashboard/site-visits/actions";
import type { AppRole } from "@/lib/auth/permissions";
import { INITIAL_SITE_VISIT_ACTION_STATE, type VisitCustomerOption, type VisitEnquiryOption, type VisitStaff } from "@/lib/site-visits/types";

const input = "min-h-12 w-full rounded-md border border-line bg-paper px-3 text-base";

export function SiteVisitForm({ customers, enquiries, siteStaff, role, initialCustomerId = "", initialEnquiryId = "" }: { customers: VisitCustomerOption[]; enquiries: VisitEnquiryOption[]; siteStaff: VisitStaff[]; role: AppRole; initialCustomerId?: string; initialEnquiryId?: string }) {
  const initialCustomer = customers.find((item) => item.id === initialCustomerId);
  const [customerId, setCustomerId] = useState(initialCustomerId);
  const [enquiryId, setEnquiryId] = useState(initialEnquiryId);
  const [address, setAddress] = useState(initialCustomer?.address || "");
  const [area, setArea] = useState(initialCustomer?.area || "");
  const [emirate, setEmirate] = useState(initialCustomer?.emirate || "");
  const [contactPhone, setContactPhone] = useState(initialCustomer?.phone || initialCustomer?.whatsapp_number || "");
  const [state, action, pending] = useActionState(createSiteVisitAction, INITIAL_SITE_VISIT_ACTION_STATE);
  const linkedEnquiries = useMemo(() => enquiries.filter((item) => !customerId || item.customer_id === customerId), [customerId, enquiries]);
  function chooseCustomer(id: string) {
    setCustomerId(id); setEnquiryId(""); const customer = customers.find((item) => item.id === id);
    setAddress(customer?.address || ""); setArea(customer?.area || ""); setEmirate(customer?.emirate || ""); setContactPhone(customer?.phone || customer?.whatsapp_number || "");
  }
  return <form action={action} className="space-y-6">
    {state.message && <p role="status" className={`rounded-md border p-3 text-sm ${state.status === "error" ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{state.message}</p>}
    <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Customer and opportunity</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Customer<select name="customer_id" required value={customerId} onChange={(event) => chooseCustomer(event.target.value)} className={input}><option value="">Choose customer</option>{customers.map((item) => <option key={item.id} value={item.id}>{item.name} — {item.phone || "No phone"}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Linked enquiry <span className="font-normal text-stone">optional</span><select name="enquiry_id" value={enquiryId} onChange={(event) => setEnquiryId(event.target.value)} className={input}><option value="">No linked enquiry</option>{linkedEnquiries.map((item) => <option key={item.id} value={item.id}>ENQ-{String(item.enquiry_number).padStart(6, "0")} — {item.product?.name || item.subject || "General enquiry"}</option>)}</select></label></div></section>
    <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Schedule and site</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Visit date and time<input className={input} name="scheduled_at" type="datetime-local" required /></label><label className="grid gap-2 text-sm font-medium">Assigned Site Team<select className={input} name="assigned_to" disabled={role !== "admin"} defaultValue=""><option value="">Unassigned</option>{siteStaff.map((person) => <option key={person.id} value={person.id}>{person.full_name}</option>)}</select>{role !== "admin" && <span className="text-xs font-normal text-stone">Management assigns Site Team staff after the request is created.</span>}</label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Site address<textarea className={`${input} min-h-24 py-3`} name="site_address" required maxLength={500} value={address} onChange={(event) => setAddress(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">Area<input className={input} name="area" maxLength={120} value={area} onChange={(event) => setArea(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium">Emirate<input className={input} name="emirate" maxLength={80} value={emirate} onChange={(event) => setEmirate(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Google Maps link <span className="font-normal text-stone">optional</span><input className={input} name="location_url" type="url" inputMode="url" placeholder="https://maps.google.com/…" maxLength={1000} /></label></div></section>
    <section className="border-y border-line bg-paper px-4 py-5 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Visit contact and handoff</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium">Contact person <span className="font-normal text-stone">optional</span><input className={input} name="contact_person" maxLength={160} /></label><label className="grid gap-2 text-sm font-medium">Contact phone <span className="font-normal text-stone">optional</span><input className={input} name="contact_phone" inputMode="tel" maxLength={40} value={contactPhone} onChange={(event) => setContactPhone(event.target.value)} /></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Preparation notes<textarea className={`${input} min-h-24 py-3`} name="notes" maxLength={8000} /></label><label className="grid gap-2 text-sm font-medium">Next action<input className={input} name="next_action" maxLength={300} placeholder="Confirm access with customer" /></label><label className="grid gap-2 text-sm font-medium">Next action due<input className={input} name="next_action_at" type="datetime-local" /></label></div></section>
    <button disabled={pending} className="min-h-12 rounded-md bg-graphite px-5 text-sm font-semibold text-white disabled:opacity-50">{pending ? "Creating visit…" : role === "sales" ? "Request site visit" : "Create site visit"}</button>
  </form>;
}
