import type { AppRole } from "@/lib/auth/permissions";

const now = "2026-09-17T10:00:00.000Z";
const day = (offset: number) => `2026-09-${String(17 - offset).padStart(2, "0")}T10:00:00.000Z`;

export const DEMO_STAFF = [
  { id: "demo-profile-alex-morgan", full_name: "Alex Morgan", role: "admin" as AppRole },
  { id: "demo-profile-jordan-lee", full_name: "Jordan Lee", role: "sales" as AppRole },
  { id: "demo-profile-sam-rivera", full_name: "Sam Rivera", role: "site_team" as AppRole },
  { id: "demo-profile-taylor-kim", full_name: "Taylor Kim", role: "accounts" as AppRole },
];

export const DEMO_CUSTOMERS = [
  { id: "demo-customer-001", name: "Maya Chen", phone: "+971 50 000 0101", whatsapp_number: "+971 50 000 0101", email: "maya.chen@example.com", company_name: null, customer_type: "individual", address: "Palm Jumeirah, Dubai", area: "Palm Jumeirah", emirate: "Dubai", notes: "Prefers evening site visits.", source: "Website", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, archived_at: null, created_at: day(12), updated_at: day(1) },
  { id: "demo-customer-002", name: "Northline Hospitality", phone: "+971 50 000 0102", whatsapp_number: "+971 50 000 0102", email: "projects@northline.example.com", company_name: "Northline Hospitality", customer_type: "company", address: "Business Bay, Dubai", area: "Business Bay", emirate: "Dubai", notes: "Two-phase terrace programme.", source: "Referral", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, archived_at: null, created_at: day(18), updated_at: day(2) },
  { id: "demo-customer-003", name: "Omar Haddad", phone: "+971 50 000 0103", whatsapp_number: "+971 50 000 0103", email: "omar.haddad@example.com", company_name: null, customer_type: "individual", address: "Arabian Ranches, Dubai", area: "Arabian Ranches", emirate: "Dubai", notes: null, source: "Phone", assigned_to: null, assigned: null, archived_at: null, created_at: day(8), updated_at: day(3) },
  { id: "demo-customer-004", name: "Lina Farouk", phone: "+971 50 000 0104", whatsapp_number: "+971 50 000 0104", email: "lina.farouk@example.com", company_name: null, customer_type: "individual", address: "Jumeirah, Dubai", area: "Jumeirah", emirate: "Dubai", notes: "Interested in integrated lighting.", source: "Instagram", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, archived_at: null, created_at: day(5), updated_at: day(1) },
];

export const DEMO_PRODUCTS = [
  { id: "demo-product-001", name: "Linea Motorised Pergola", product_code: "LP-100", category_id: "demo-category-001", category: { id: "demo-category-001", name: "Louvered Pergolas" }, pricing_mode: "from", price: 45000, currency: "AED", is_published: true, is_featured: true, archived_at: null, updated_at: now, image_url: null, images: [] },
  { id: "demo-product-002", name: "Breeze Retractable Roof", product_code: "RR-200", category_id: "demo-category-002", category: { id: "demo-category-002", name: "Retractable Systems" }, pricing_mode: "from", price: 27000, currency: "AED", is_published: true, is_featured: false, archived_at: null, updated_at: day(1), image_url: null, images: [] },
  { id: "demo-product-003", name: "Integrated LED Lighting", product_code: "AC-300", category_id: "demo-category-003", category: { id: "demo-category-003", name: "Accessories" }, pricing_mode: "fixed", price: 3200, currency: "AED", is_published: true, is_featured: false, archived_at: null, updated_at: day(2), image_url: null, images: [] },
  { id: "demo-product-004", name: "Motorised Side Screen", product_code: "AC-310", category_id: "demo-category-003", category: { id: "demo-category-003", name: "Accessories" }, pricing_mode: "from", price: 4800, currency: "AED", is_published: true, is_featured: false, archived_at: null, updated_at: day(3), image_url: null, images: [] },
];

export const DEMO_CATEGORIES = [
  { id: "demo-category-001", name: "Louvered Pergolas", slug: "louvered-pergolas", description: "Architectural systems for year-round outdoor living.", is_active: true, sort_order: 1, archived_at: null, image_url: null, updated_at: now },
  { id: "demo-category-002", name: "Retractable Systems", slug: "retractable-systems", description: "Flexible shade and weather-control systems.", is_active: true, sort_order: 2, archived_at: null, image_url: null, updated_at: day(1) },
  { id: "demo-category-003", name: "Accessories", slug: "accessories", description: "Lighting, screens, sensors, and finishing details.", is_active: true, sort_order: 3, archived_at: null, image_url: null, updated_at: day(2) },
];

export const DEMO_ENQUIRIES = [
  { id: "demo-enquiry-001", enquiry_number: 2101, customer_id: DEMO_CUSTOMERS[0].id, customer: { id: DEMO_CUSTOMERS[0].id, name: DEMO_CUSTOMERS[0].name, phone: DEMO_CUSTOMERS[0].phone }, product_id: DEMO_PRODUCTS[0].id, product: { id: DEMO_PRODUCTS[0].id, name: DEMO_PRODUCTS[0].name }, enquiry_type: "catalogue", subject: "Motorised pergola for a Palm terrace", message: "Looking for a shaded entertaining area with lighting.", source: "Website", status: "site_visit_required", priority: "high", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, follow_up_at: day(-1), next_action: "Confirm site measurements", internal_notes: null, archived_at: null, created_at: day(2), updated_at: day(1), lastActivity: day(1) },
  { id: "demo-enquiry-002", enquiry_number: 2102, customer_id: DEMO_CUSTOMERS[1].id, customer: { id: DEMO_CUSTOMERS[1].id, name: DEMO_CUSTOMERS[1].name, phone: DEMO_CUSTOMERS[1].phone }, product_id: DEMO_PRODUCTS[1].id, product: { id: DEMO_PRODUCTS[1].id, name: DEMO_PRODUCTS[1].name }, enquiry_type: "general", subject: "Boutique hotel terrace programme", message: "Please scope three rooftop areas.", source: "Referral", status: "quotation", priority: "normal", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, follow_up_at: null, next_action: "Prepare revision two", internal_notes: null, archived_at: null, created_at: day(4), updated_at: day(2), lastActivity: day(2) },
  { id: "demo-enquiry-003", enquiry_number: 2103, customer_id: DEMO_CUSTOMERS[2].id, customer: { id: DEMO_CUSTOMERS[2].id, name: DEMO_CUSTOMERS[2].name, phone: DEMO_CUSTOMERS[2].phone }, product_id: null, product: null, enquiry_type: "manual", subject: "Outdoor kitchen cover", message: "Exploring options for a new villa.", source: "Phone", status: "new", priority: "normal", assigned_to: null, assigned: null, follow_up_at: day(-2), next_action: "Assign discovery call", internal_notes: null, archived_at: null, created_at: day(1), updated_at: day(1), lastActivity: day(1) },
  { id: "demo-enquiry-004", enquiry_number: 2104, customer_id: DEMO_CUSTOMERS[3].id, customer: { id: DEMO_CUSTOMERS[3].id, name: DEMO_CUSTOMERS[3].name, phone: DEMO_CUSTOMERS[3].phone }, product_id: DEMO_PRODUCTS[2].id, product: { id: DEMO_PRODUCTS[2].id, name: DEMO_PRODUCTS[2].name }, enquiry_type: "catalogue", subject: "Lighting upgrade", message: "Can we add lighting to the existing concept?", source: "Instagram", status: "contacted", priority: "low", assigned_to: DEMO_STAFF[1].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, follow_up_at: null, next_action: "Send lighting options", internal_notes: null, archived_at: null, created_at: day(3), updated_at: day(2), lastActivity: day(2) },
];

export const DEMO_PROJECTS = [
  { id: "demo-project-001", project_number: "UP-DEMO-0001", customer_id: DEMO_CUSTOMERS[0].id, customer: { id: DEMO_CUSTOMERS[0].id, name: DEMO_CUSTOMERS[0].name, phone: DEMO_CUSTOMERS[0].phone }, status: "active", project_value: 48825, currency: "AED", current_stage: { id: "demo-stage-001", stage_key: "manufacturing", name: "Manufacturing", status: "in_progress" }, progress: 62, installation_date: "2026-09-29", expected_completion_date: "2026-10-05", handover_status: "pending", assigned_salesperson: DEMO_STAFF[1].id, assignments: [{ id: "demo-assignment-001", user_id: DEMO_STAFF[2].id, assignment_role: "site_team", user: DEMO_STAFF[2] }], created_at: day(8), updated_at: now },
  { id: "demo-project-002", project_number: "UP-DEMO-0002", customer_id: DEMO_CUSTOMERS[1].id, customer: { id: DEMO_CUSTOMERS[1].id, name: DEMO_CUSTOMERS[1].name, phone: DEMO_CUSTOMERS[1].phone }, status: "active", project_value: 112400, currency: "AED", current_stage: { id: "demo-stage-002", stage_key: "installation", name: "Installation", status: "in_progress" }, progress: 84, installation_date: "2026-09-23", expected_completion_date: "2026-09-25", handover_status: "ready", assigned_salesperson: DEMO_STAFF[1].id, assignments: [{ id: "demo-assignment-002", user_id: DEMO_STAFF[2].id, assignment_role: "site_team", user: DEMO_STAFF[2] }], created_at: day(20), updated_at: day(1) },
  { id: "demo-project-003", project_number: "UP-DEMO-0003", customer_id: DEMO_CUSTOMERS[2].id, customer: { id: DEMO_CUSTOMERS[2].id, name: DEMO_CUSTOMERS[2].name, phone: DEMO_CUSTOMERS[2].phone }, status: "completed", project_value: 33600, currency: "AED", current_stage: { id: "demo-stage-003", stage_key: "completed", name: "Completed", status: "completed" }, progress: 100, installation_date: "2026-08-14", expected_completion_date: "2026-08-22", handover_status: "completed", assigned_salesperson: DEMO_STAFF[1].id, assignments: [], created_at: day(40), updated_at: day(6) },
];

export const DEMO_VISITS = [
  { id: "demo-visit-001", visit_number: 3101, customer: { id: DEMO_CUSTOMERS[0].id, name: DEMO_CUSTOMERS[0].name, phone: DEMO_CUSTOMERS[0].phone }, customer_id: DEMO_CUSTOMERS[0].id, enquiry: { id: DEMO_ENQUIRIES[0].id, enquiry_number: DEMO_ENQUIRIES[0].enquiry_number }, site_address: "Palm Jumeirah, Dubai", scheduled_at: "2026-09-19T08:00:00.000Z", status: "scheduled", assigned: { id: DEMO_STAFF[2].id, full_name: DEMO_STAFF[2].full_name }, assigned_to: DEMO_STAFF[2].id, created_at: day(1), updated_at: day(1) },
  { id: "demo-visit-002", visit_number: 3102, customer: { id: DEMO_CUSTOMERS[1].id, name: DEMO_CUSTOMERS[1].name, phone: DEMO_CUSTOMERS[1].phone }, customer_id: DEMO_CUSTOMERS[1].id, enquiry: { id: DEMO_ENQUIRIES[1].id, enquiry_number: DEMO_ENQUIRIES[1].enquiry_number }, site_address: "Business Bay, Dubai", scheduled_at: "2026-09-20T10:00:00.000Z", status: "completed", assigned: { id: DEMO_STAFF[2].id, full_name: DEMO_STAFF[2].full_name }, assigned_to: DEMO_STAFF[2].id, created_at: day(4), updated_at: day(3) },
];

export const DEMO_QUOTATIONS = [
  { id: "demo-quote-001", quotation_number: "UP-Q-DEMO-001", revision_number: 2, customer: { id: DEMO_CUSTOMERS[0].id, name: DEMO_CUSTOMERS[0].name, phone: DEMO_CUSTOMERS[0].phone }, customer_id: DEMO_CUSTOMERS[0].id, project: { id: DEMO_PROJECTS[0].id, project_number: DEMO_PROJECTS[0].project_number }, project_id: DEMO_PROJECTS[0].id, status: "approved", total: 48825, currency: "AED", issue_date: day(3), valid_until: "2026-09-30", created_at: day(3), updated_at: day(2), assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name } },
  { id: "demo-quote-002", quotation_number: "UP-Q-DEMO-002", revision_number: 1, customer: { id: DEMO_CUSTOMERS[1].id, name: DEMO_CUSTOMERS[1].name, phone: DEMO_CUSTOMERS[1].phone }, customer_id: DEMO_CUSTOMERS[1].id, project: { id: DEMO_PROJECTS[1].id, project_number: DEMO_PROJECTS[1].project_number }, project_id: DEMO_PROJECTS[1].id, status: "sent", total: 112400, currency: "AED", issue_date: day(1), valid_until: "2026-09-28", created_at: day(1), updated_at: day(1), assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name } },
];

export const DEMO_TASKS = [
  { id: "demo-task-001", title: "Confirm Palm terrace measurements", description: "Review the site-visit checklist before the client call.", kind: "enquiry_follow_up", status: "open", priority: "high", due_at: "2026-09-19T08:00:00.000Z", completed_at: null, customer_id: DEMO_CUSTOMERS[0].id, enquiry_id: DEMO_ENQUIRIES[0].id, project_id: null, site_visit_id: DEMO_VISITS[0].id, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, assigned_to: DEMO_STAFF[1].id, project: null, enquiry: { id: DEMO_ENQUIRIES[0].id, enquiry_number: DEMO_ENQUIRIES[0].enquiry_number }, site_visit: { id: DEMO_VISITS[0].id, visit_number: DEMO_VISITS[0].visit_number } },
  { id: "demo-task-002", title: "Review installation readiness", description: "Check final materials before dispatch.", kind: "project_task", status: "in_progress", priority: "normal", due_at: "2026-09-22T08:00:00.000Z", completed_at: null, customer_id: DEMO_CUSTOMERS[1].id, enquiry_id: null, project_id: DEMO_PROJECTS[1].id, site_visit_id: null, assigned: { id: DEMO_STAFF[2].id, full_name: DEMO_STAFF[2].full_name }, assigned_to: DEMO_STAFF[2].id, project: { id: DEMO_PROJECTS[1].id, project_number: DEMO_PROJECTS[1].project_number }, enquiry: null, site_visit: null },
  { id: "demo-task-003", title: "Send lighting options", description: "Share the accessory selection with the customer.", kind: "enquiry_follow_up", status: "completed", priority: "low", due_at: day(2), completed_at: day(1), customer_id: DEMO_CUSTOMERS[3].id, enquiry_id: DEMO_ENQUIRIES[3].id, project_id: null, site_visit_id: null, assigned: { id: DEMO_STAFF[1].id, full_name: DEMO_STAFF[1].full_name }, assigned_to: DEMO_STAFF[1].id, project: null, enquiry: { id: DEMO_ENQUIRIES[3].id, enquiry_number: DEMO_ENQUIRIES[3].enquiry_number }, site_visit: null },
];

export const DEMO_FEEDBACK = [
  { id: "demo-feedback-001", project_id: DEMO_PROJECTS[2].id, project: { id: DEMO_PROJECTS[2].id, project_number: DEMO_PROJECTS[2].project_number, customer: { id: DEMO_CUSTOMERS[2].id, name: DEMO_CUSTOMERS[2].name } }, rating: 5, comment: "The handover was clear and the installation team was excellent.", status: "published", created_at: day(5), updated_at: day(4) },
  { id: "demo-feedback-002", project_id: DEMO_PROJECTS[1].id, project: { id: DEMO_PROJECTS[1].id, project_number: DEMO_PROJECTS[1].project_number, customer: { id: DEMO_CUSTOMERS[1].id, name: DEMO_CUSTOMERS[1].name } }, rating: 4, comment: "Strong progress update and a clean site visit.", status: "received", created_at: day(1), updated_at: day(1) },
];

export const DEMO_FINANCE = { received_this_month: 82450, outstanding: 60350, overdue: 18400, due_soon: 21950, received_today: 7200, received: 168900, project_value: 294825 };

export const DEMO_PROFILE = { id: "demo-profile-alex-morgan", fullName: "Alex Morgan", email: "alex.morgan@example.com", role: "admin" as const };
