import Link from "next/link";
import { ClipboardCheck, Plus } from "lucide-react";
import { PageHeading } from "@/components/ui/page-heading";
import { requireRole } from "@/lib/auth/dal";
import { formatDate } from "@/lib/crm/presentation";
import { getCustomerOptions, getEnquiries, getStaffDirectory } from "@/lib/crm/queries";
import { getProjects } from "@/lib/projects/queries";
import { getTaskQueue } from "@/lib/tasks/queries";
import { completeReminderAction, createReminderAction, rescheduleReminderAction } from "./actions";

const reminderTypes = ["Enquiry follow-up", "Customer call", "Meeting", "Site visit", "Quotation follow-up", "Payment follow-up", "General reminder"];
function taskHref(item: Awaited<ReturnType<typeof getTaskQueue>>[number]) { if(item.project_id) return `/dashboard/projects/${item.project_id}`; if(item.site_visit_id) return `/dashboard/site-visits/${item.site_visit_id}`; if(item.enquiry_id) return `/dashboard/enquiries/${item.enquiry_id}`; if(item.customer_id) return `/dashboard/customers/${item.customer_id}`; return "/dashboard/tasks"; }
function localDateTime(value?: string | null) { return value ? new Date(new Date(value).getTime() + 4 * 60 * 60 * 1000).toISOString().slice(0,16) : ""; }
function bucket(item: {status:string; due_at:string|null}) { if(item.status === "completed") return "completed"; if(!item.due_at) return "upcoming"; const today = new Intl.DateTimeFormat("en-CA", {timeZone:"Asia/Dubai"}).format(new Date()); const day=item.due_at.slice(0,10); return day < today ? "overdue" : day === today ? "today" : "upcoming"; }

export default async function TasksPage({searchParams}:PageProps<"/dashboard/tasks">){
  const [profile, params, tasks, staff, customers, enquiries, projects] = await Promise.all([requireRole(["admin","sales"]), searchParams, getTaskQueue(), getStaffDirectory(), getCustomerOptions(), getEnquiries({}), getProjects({})]);
  const view = typeof params.view === "string" ? params.view : "all";
  const reminders = tasks.filter((task) => task.reminder_type);
  const visible = reminders.filter((item) => view === "all" || bucket(item) === view || (view === "mine" && item.assigned?.id === profile.id));
  return <div className="space-y-7"><PageHeading title="Reminders" description="Calls, meetings, follow-ups, and important dates in one practical queue." action={<a href="#new-reminder" className="inline-flex min-h-11 items-center gap-2 rounded-md bg-graphite px-4 text-sm font-semibold text-white"><Plus size={17}/>Add reminder</a>} />
    <div className="flex gap-2 overflow-x-auto">{[["all","All"],["overdue","Overdue"],["today","Today"],["upcoming","Upcoming"],["completed","Completed"],["mine","Assigned to me"]].map(([key,label])=><Link key={key} href={key==="all"?"/dashboard/tasks":`/dashboard/tasks?view=${key}`} className={`shrink-0 rounded-full border px-4 py-2 text-sm ${view===key?"border-graphite bg-graphite text-white":"border-line bg-paper"}`}>{label}</Link>)}</div>
    <section id="new-reminder" className="border-y border-line bg-paper px-4 py-5 scroll-mt-6 sm:rounded-lg sm:border sm:p-6"><h2 className="text-lg font-semibold">Add reminder</h2><form action={createReminderAction} className="mt-5 grid gap-4 sm:grid-cols-2"><label className="grid gap-2 text-sm font-medium sm:col-span-2">Title<input className="min-h-11 rounded-md border border-line px-3 text-base" name="title" required maxLength={200} placeholder="Meeting with customer" /></label><label className="grid gap-2 text-sm font-medium">Type<select className="min-h-11 rounded-md border border-line bg-paper px-3 text-base" name="reminder_type">{reminderTypes.map(type=><option key={type}>{type}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Date and time<input className="min-h-11 rounded-md border border-line px-3 text-base" name="due_at" type="datetime-local" required /></label><label className="grid gap-2 text-sm font-medium">Assigned partner<select className="min-h-11 rounded-md border border-line bg-paper px-3 text-base" name="assigned_to" defaultValue={profile.id}>{staff.map(person=><option key={person.id} value={person.id}>{person.full_name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Customer <span className="font-normal text-stone">optional</span><select className="min-h-11 rounded-md border border-line bg-paper px-3 text-base" name="customer_id"><option value="">No linked customer</option>{customers.map(customer=><option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Enquiry <span className="font-normal text-stone">optional</span><select className="min-h-11 rounded-md border border-line bg-paper px-3 text-base" name="enquiry_id"><option value="">No linked enquiry</option>{enquiries.map(item=><option key={item.id} value={item.id}>ENQ-{String(item.enquiry_number).padStart(6,"0")}</option>)}</select></label><label className="grid gap-2 text-sm font-medium">Project <span className="font-normal text-stone">optional</span><select className="min-h-11 rounded-md border border-line bg-paper px-3 text-base" name="project_id"><option value="">No linked project</option>{projects.map(project=><option key={project.id} value={project.id}>{project.project_number}</option>)}</select></label><label className="grid gap-2 text-sm font-medium sm:col-span-2">Note <span className="font-normal text-stone">optional</span><textarea className="min-h-24 rounded-md border border-line px-3 py-2 text-base" name="description" maxLength={2000}/></label><button className="min-h-11 rounded-md bg-graphite px-4 text-sm font-semibold text-white sm:w-fit">Save reminder</button></form></section>
    <section className="overflow-hidden rounded-lg border border-line bg-paper">{visible.length?<div className="divide-y divide-line">{visible.map(item=><article key={item.id} className="grid gap-3 px-4 py-4 sm:grid-cols-[minmax(0,1fr)_10rem_10rem] sm:items-center sm:px-5"><div className="min-w-0"><Link href={taskHref(item)} className="font-semibold hover:text-brass-dark">{item.title}</Link><p className="mt-1 text-xs text-stone">{item.reminder_type} · {item.assigned?.full_name || "Unassigned"}{item.description ? ` · ${item.description}` : ""}</p></div><span className={`text-xs ${bucket(item)==="overdue"?"text-red-700":"text-stone"}`}>{formatDate(item.due_at,true)}</span><div className="flex flex-wrap gap-3 sm:justify-end">{item.status!=="completed"&&<><form action={completeReminderAction}><input type="hidden" name="id" value={item.id}/><button className="min-h-10 text-sm font-medium text-emerald-700">Mark done</button></form><form action={rescheduleReminderAction} className="flex items-center gap-2"><input className="min-h-10 rounded-md border border-line px-2 text-sm" name="due_at" type="datetime-local" defaultValue={localDateTime(item.due_at)} required/><input type="hidden" name="id" value={item.id}/><button className="min-h-10 text-sm font-medium text-brass-dark">Reschedule</button></form></>}</div></article>)}</div>:<div className="px-5 py-12 text-center"><ClipboardCheck className="mx-auto text-brass-dark"/><h2 className="mt-4 font-semibold">No reminders in this view</h2><p className="mt-2 text-sm text-stone">Create one above to keep important work visible.</p></div>}</section></div>;
}
