-- Universal Pergola Phase 2C: site visits, structured measurements, private photos and handoff workflow.

alter type public.site_visit_status add value if not exists 'no_show' after 'rescheduled';
alter type public.task_kind add value if not exists 'site_visit_follow_up';

alter table public.site_visits
  add column visit_number bigint generated by default as identity (start with 2001),
  add column area text,
  add column emirate text,
  add column contact_person text,
  add column contact_phone text,
  add column measurement_summary text,
  add column actual_started_at timestamptz,
  add constraint site_visits_visit_number_key unique (visit_number),
  add constraint site_visits_address_length check (char_length(trim(site_address)) between 2 and 500),
  add constraint site_visits_location_length check (
    (area is null or char_length(area) <= 120)
    and (emirate is null or char_length(emirate) <= 80)
  ),
  add constraint site_visits_contact_length check (
    (contact_person is null or char_length(contact_person) <= 160)
    and (contact_phone is null or char_length(contact_phone) <= 40)
  ),
  add constraint site_visits_maps_url check (
    location_url is null
    or lower(location_url) ~ '^https://(www\.)?(google\.com/maps|maps\.google\.com/|maps\.app\.goo\.gl/|goo\.gl/maps/)'
  ),
  add constraint site_visits_text_lengths check (
    (measurement_summary is null or char_length(measurement_summary) <= 4000)
    and (notes is null or char_length(notes) <= 8000)
    and (next_action is null or char_length(next_action) <= 300)
  );

alter table public.site_visit_photos
  add column sort_order integer not null default 0,
  add column photo_type text,
  add column mime_type text,
  add column file_size bigint,
  add constraint site_visit_photos_caption_length check (caption is null or char_length(caption) <= 300),
  add constraint site_visit_photos_type_length check (photo_type is null or char_length(photo_type) <= 80),
  add constraint site_visit_photos_mime check (mime_type is null or mime_type in ('image/jpeg', 'image/png', 'image/webp')),
  add constraint site_visit_photos_size check (file_size is null or file_size between 1 and 10485760),
  add constraint site_visit_photos_order check (sort_order between -10000 and 10000);

create table public.site_visit_measurements (
  id uuid primary key default gen_random_uuid(),
  site_visit_id uuid not null references public.site_visits(id) on delete cascade,
  label text not null,
  width numeric(12,3),
  height numeric(12,3),
  length numeric(12,3),
  unit text not null default 'mm',
  quantity numeric(10,2) not null default 1,
  notes text,
  sort_order integer not null default 0,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_visit_measurements_label_length check (char_length(trim(label)) between 2 and 120),
  constraint site_visit_measurements_unit check (unit in ('mm', 'cm', 'm')),
  constraint site_visit_measurements_values check (
    (width is null or width > 0)
    and (height is null or height > 0)
    and (length is null or length > 0)
    and (width is not null or height is not null or length is not null)
  ),
  constraint site_visit_measurements_quantity check (quantity > 0 and quantity <= 1000),
  constraint site_visit_measurements_notes_length check (notes is null or char_length(notes) <= 1000),
  constraint site_visit_measurements_order check (sort_order between -10000 and 10000)
);

create table public.site_visit_activities (
  id uuid primary key default gen_random_uuid(),
  site_visit_id uuid not null references public.site_visits(id) on delete cascade,
  activity_type text not null,
  note text,
  occurred_at timestamptz not null default now(),
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_visit_activities_type_length check (char_length(trim(activity_type)) between 2 and 80),
  constraint site_visit_activities_note_length check (note is null or char_length(note) <= 4000)
);

create index site_visits_customer_schedule_idx on public.site_visits(customer_id, scheduled_at desc) where archived_at is null;
create index site_visits_enquiry_schedule_idx on public.site_visits(enquiry_id, scheduled_at desc) where enquiry_id is not null and archived_at is null;
create index site_visits_created_by_idx on public.site_visits(created_by) where created_by is not null;
create index site_visits_status_schedule_idx on public.site_visits(status, scheduled_at) where archived_at is null;
create index site_visit_photos_visit_order_idx on public.site_visit_photos(site_visit_id, sort_order, created_at);
create index site_visit_photos_created_by_idx on public.site_visit_photos(created_by) where created_by is not null;
create index site_visit_measurements_visit_order_idx on public.site_visit_measurements(site_visit_id, sort_order, created_at);
create index site_visit_measurements_created_by_idx on public.site_visit_measurements(created_by) where created_by is not null;
create index site_visit_activities_visit_time_idx on public.site_visit_activities(site_visit_id, occurred_at desc);
create index site_visit_activities_created_by_idx on public.site_visit_activities(created_by) where created_by is not null;
create index tasks_site_visit_follow_up_idx on public.tasks(site_visit_id, status, due_at)
where site_visit_id is not null and archived_at is null;

create trigger site_visit_measurements_updated_at before update on public.site_visit_measurements
for each row execute function private.set_updated_at();
create trigger site_visit_activities_updated_at before update on public.site_visit_activities
for each row execute function private.set_updated_at();

alter table public.site_visit_measurements enable row level security;
alter table public.site_visit_activities enable row level security;
revoke all on public.site_visit_measurements, public.site_visit_activities from anon, authenticated;
grant select, insert, update, delete on public.site_visit_measurements, public.site_visit_activities to authenticated;
grant usage, select on sequence public.site_visits_visit_number_seq to authenticated;

create or replace function private.can_access_site_visit(target uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select case private.current_user_role()
    when 'admin' then true
    when 'sales' then true
    when 'site_team' then exists (
      select 1 from public.site_visits v
      where v.id = target and v.assigned_to = (select auth.uid()) and v.archived_at is null
    )
    else false end
$$;

revoke all on function private.can_access_site_visit(uuid) from public, anon;
grant execute on function private.can_access_site_visit(uuid) to authenticated;

create or replace function private.validate_site_visit()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  assignee_valid boolean;
  enquiry_customer uuid;
  role_name public.app_role := private.current_user_role();
  old_status text;
  new_status text := new.status::text;
begin
  if new.assigned_to is not null then
    select exists (
      select 1 from public.profiles p
      where p.id = new.assigned_to and p.status = 'active'::public.profile_status
        and p.role = 'site_team'::public.app_role
    ) into assignee_valid;
    if not assignee_valid then raise exception 'Site visits can only be assigned to active Site Team staff'; end if;
  end if;

  if new.enquiry_id is not null then
    select e.customer_id into enquiry_customer from public.enquiries e where e.id = new.enquiry_id and e.archived_at is null;
    if not found or enquiry_customer is distinct from new.customer_id then
      raise exception 'The visit customer must match the linked enquiry customer';
    end if;
  end if;

  if tg_op = 'INSERT' then
    if role_name = 'sales'::public.app_role and (
      new.created_by is distinct from (select auth.uid())
      or new.assigned_to is not null
      or new.status::text <> 'scheduled'
    ) then raise exception 'Sales can only request unassigned scheduled visits'; end if;
    return new;
  end if;

  if role_name = 'site_team'::public.app_role and (
    new.assigned_to is distinct from old.assigned_to
    or new.customer_id is distinct from old.customer_id
    or new.enquiry_id is distinct from old.enquiry_id
    or new.created_by is distinct from old.created_by
    or new.scheduled_at is distinct from old.scheduled_at
    or new.site_address is distinct from old.site_address
    or new.area is distinct from old.area
    or new.emirate is distinct from old.emirate
    or new.location_url is distinct from old.location_url
    or new.contact_person is distinct from old.contact_person
    or new.contact_phone is distinct from old.contact_phone
    or new.archived_at is distinct from old.archived_at
  ) then raise exception 'Site Team cannot reassign or relink a visit'; end if;

  old_status := old.status::text;
  if new_status is distinct from old_status and not (
    (old_status = 'scheduled' and new_status in ('confirmed', 'rescheduled', 'cancelled', 'no_show'))
    or (old_status = 'confirmed' and new_status in ('in_progress', 'rescheduled', 'cancelled', 'no_show'))
    or (old_status = 'in_progress' and new_status in ('completed', 'cancelled'))
    or (old_status = 'rescheduled' and new_status in ('scheduled', 'confirmed', 'cancelled', 'no_show'))
    or (old_status = 'no_show' and new_status in ('rescheduled', 'cancelled'))
  ) then raise exception 'Invalid site visit status transition from % to %', old_status, new_status; end if;

  if new_status = 'in_progress' and old_status <> 'in_progress' then
    new.actual_started_at := coalesce(new.actual_started_at, now());
  end if;
  if new_status = 'completed' and old_status <> 'completed' then
    if new.assigned_to is null then raise exception 'Assign Site Team staff before completing the visit'; end if;
    if nullif(trim(coalesce(new.notes, '')), '') is null
       and nullif(trim(coalesce(new.measurement_summary, '')), '') is null
       and not exists (select 1 from public.site_visit_measurements m where m.site_visit_id = new.id) then
      raise exception 'Add a visit note, measurement summary, or measurement before completion';
    end if;
    new.completed_at := coalesce(new.completed_at, now());
  end if;
  return new;
end;
$$;

create trigger site_visits_validate_workflow before insert or update on public.site_visits
for each row execute function private.validate_site_visit();

create or replace function private.validate_site_visit_measurement()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'UPDATE' and new.site_visit_id is distinct from old.site_visit_id then
    raise exception 'Measurements cannot be moved between visits';
  end if;
  if private.current_user_role() = 'site_team'::public.app_role and new.created_by is distinct from (select auth.uid()) then
    raise exception 'Site Team must create measurements as themselves';
  end if;
  return new;
end;
$$;

create trigger site_visit_measurements_validate before insert or update on public.site_visit_measurements
for each row execute function private.validate_site_visit_measurement();

create or replace function private.validate_site_visit_photo()
returns trigger language plpgsql security definer set search_path = '' as $$
declare path_value text := case when tg_op = 'DELETE' then old.storage_path else new.storage_path end;
declare visit_value uuid := case when tg_op = 'DELETE' then old.site_visit_id else new.site_visit_id end;
begin
  if path_value !~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(jpg|jpeg|png|webp)$'
     or split_part(path_value, '/', 1) <> visit_value::text then
    raise exception 'Invalid site photo path';
  end if;
  if tg_op = 'UPDATE' and (new.site_visit_id is distinct from old.site_visit_id or new.storage_path is distinct from old.storage_path) then
    raise exception 'Site photos cannot be moved between visits';
  end if;
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger site_visit_photos_validate before insert or update on public.site_visit_photos
for each row execute function private.validate_site_visit_photo();

create or replace function private.validate_crm_assignee()
returns trigger language plpgsql security definer set search_path = '' as $$
declare
  assignee_valid boolean;
  expected_customer uuid;
  expected_enquiry uuid;
begin
  if tg_table_name in ('customers', 'enquiries') and new.assigned_to is not null then
    select exists (select 1 from public.profiles p where p.id = new.assigned_to and p.status = 'active'::public.profile_status and p.role = any(array['admin'::public.app_role, 'sales'::public.app_role])) into assignee_valid;
    if not assignee_valid then raise exception 'CRM work can only be assigned to active Management or Sales staff'; end if;
  elsif tg_table_name = 'tasks' and new.assigned_to is not null then
    select exists (
      select 1 from public.profiles p where p.id = new.assigned_to and p.status = 'active'::public.profile_status
      and (
        (new.kind::text = 'enquiry_follow_up' and p.role = any(array['admin'::public.app_role, 'sales'::public.app_role]))
        or (new.kind::text = 'site_visit_follow_up' and p.role = any(array['admin'::public.app_role, 'sales'::public.app_role, 'site_team'::public.app_role]))
        or (new.kind::text = 'general')
      )
    ) into assignee_valid;
    if not assignee_valid then raise exception 'Choose an active staff member permitted for this task'; end if;
  end if;

  if tg_table_name = 'tasks' and new.kind::text = 'enquiry_follow_up' then
    if new.enquiry_id is null then raise exception 'An enquiry follow-up must be linked to an enquiry'; end if;
    select e.customer_id into expected_customer from public.enquiries e where e.id = new.enquiry_id;
    if not found or new.customer_id is distinct from expected_customer then raise exception 'The follow-up customer must match the enquiry customer'; end if;
    if private.current_user_role() = 'sales'::public.app_role and new.assigned_to is distinct from (select auth.uid()) then raise exception 'Sales staff can only assign new follow-ups to themselves'; end if;
  elsif tg_table_name = 'tasks' and new.kind::text = 'site_visit_follow_up' then
    if new.site_visit_id is null then raise exception 'A site follow-up must be linked to a visit'; end if;
    select v.customer_id, v.enquiry_id into expected_customer, expected_enquiry from public.site_visits v where v.id = new.site_visit_id;
    if not found or new.customer_id is distinct from expected_customer or new.enquiry_id is distinct from expected_enquiry then raise exception 'The follow-up links must match the site visit'; end if;
    if private.current_user_role() = 'site_team'::public.app_role and new.assigned_to is distinct from (select auth.uid()) then raise exception 'Site Team can only assign new follow-ups to themselves'; end if;
  end if;
  return new;
end;
$$;

create or replace function private.log_site_visit_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare event_name text;
declare detail text;
begin
  if tg_op = 'INSERT' then
    event_name := 'visit_created'; detail := 'Site visit created';
  elsif new.assigned_to is distinct from old.assigned_to then
    event_name := 'visit_assigned'; detail := 'Site Team assignment changed';
  elsif new.scheduled_at is distinct from old.scheduled_at then
    event_name := 'schedule_changed'; detail := 'Visit schedule changed';
  elsif new.status is distinct from old.status then
    event_name := case new.status::text when 'in_progress' then 'visit_started' when 'completed' then 'visit_completed' when 'cancelled' then 'visit_cancelled' when 'rescheduled' then 'visit_rescheduled' when 'no_show' then 'visit_no_show' else 'status_changed' end;
    detail := 'Status changed from ' || replace(old.status::text, '_', ' ') || ' to ' || replace(new.status::text, '_', ' ');
  else
    event_name := 'visit_updated'; detail := 'Visit details updated';
  end if;
  insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by)
  values (new.id, event_name, detail, (select auth.uid()));
  if new.enquiry_id is not null and tg_op = 'INSERT' then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
    values (new.enquiry_id, 'site_visit_created', detail, (select auth.uid()));
  elsif new.enquiry_id is not null and new.status::text = 'completed' and old.status::text <> 'completed' then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
    values (new.enquiry_id, 'site_visit_completed', detail, (select auth.uid()));
  end if;
  return new;
end;
$$;

create or replace function private.log_site_measurement_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare visit_id uuid;
declare measurement_label text;
begin
  if tg_op = 'DELETE' then visit_id := old.site_visit_id; measurement_label := old.label;
  else visit_id := new.site_visit_id; measurement_label := new.label; end if;
  insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by)
  values (visit_id, case tg_op when 'INSERT' then 'measurement_added' when 'UPDATE' then 'measurement_updated' else 'measurement_removed' end, measurement_label, (select auth.uid()));
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function private.log_site_photo_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare visit_id uuid;
declare photo_note text;
begin
  if tg_op = 'DELETE' then visit_id := old.site_visit_id; photo_note := coalesce(old.caption, old.photo_type, 'Site photo');
  else visit_id := new.site_visit_id; photo_note := coalesce(new.caption, new.photo_type, 'Site photo'); end if;
  insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by)
  values (visit_id, case when tg_op = 'INSERT' then 'photo_uploaded' else 'photo_removed' end, photo_note, (select auth.uid()));
  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create or replace function private.log_site_follow_up_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.kind::text <> 'site_visit_follow_up' or new.site_visit_id is null then return new; end if;
  if tg_op = 'INSERT' then
    insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by) values (new.site_visit_id, 'follow_up_created', new.title, (select auth.uid()));
  elsif new.status = 'completed'::public.task_status and old.status <> 'completed'::public.task_status then
    insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by) values (new.site_visit_id, 'follow_up_completed', new.title, (select auth.uid()));
  elsif new.due_at is distinct from old.due_at then
    insert into public.site_visit_activities(site_visit_id, activity_type, note, created_by) values (new.site_visit_id, 'follow_up_rescheduled', new.title, (select auth.uid()));
  end if;
  return new;
end;
$$;

create or replace function private.log_site_activity_entry()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.activity_logs(actor_id, event_type, entity_type, entity_id, metadata)
  values (new.created_by, 'site_visit.' || new.activity_type, 'site_visits', new.site_visit_id, jsonb_build_object('activity_id', new.id));
  return new;
end;
$$;

drop trigger if exists site_visits_activity on public.site_visits;
create trigger site_visits_operational_activity after insert or update on public.site_visits
for each row execute function private.log_site_visit_change();
create trigger site_visit_measurements_activity after insert or update or delete on public.site_visit_measurements
for each row execute function private.log_site_measurement_change();
create trigger site_visit_photos_activity after insert or delete on public.site_visit_photos
for each row execute function private.log_site_photo_change();
create trigger tasks_site_visit_follow_up_activity after insert or update on public.tasks
for each row execute function private.log_site_follow_up_change();
create trigger site_visit_activities_global_activity after insert on public.site_visit_activities
for each row execute function private.log_site_activity_entry();

revoke all on function private.validate_site_visit(), private.validate_site_visit_measurement(), private.validate_site_visit_photo(), private.log_site_visit_change(), private.log_site_measurement_change(), private.log_site_photo_change(), private.log_site_follow_up_change(), private.log_site_activity_entry() from public, anon, authenticated;

drop policy if exists "sales reads site visits" on public.site_visits;
drop policy if exists "sales manages site visits" on public.site_visits;
drop policy if exists "site team updates assigned visits" on public.site_visits;
create policy "authorized staff reads site visits" on public.site_visits for select to authenticated
using (private.can_access_site_visit(id));
create policy "crm requests site visits" on public.site_visits for insert to authenticated
with check (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['sales'::public.app_role]) and created_by = (select auth.uid()) and assigned_to is null and status::text = 'scheduled')
);
create policy "management updates site visits" on public.site_visits for update to authenticated
using (private.has_role(array['admin'::public.app_role])) with check (private.has_role(array['admin'::public.app_role]));
create policy "site team updates assigned visits" on public.site_visits for update to authenticated
using (private.has_role(array['site_team'::public.app_role]) and assigned_to = (select auth.uid()))
with check (private.has_role(array['site_team'::public.app_role]) and assigned_to = (select auth.uid()));
create policy "management deletes site visits" on public.site_visits for delete to authenticated
using (private.has_role(array['admin'::public.app_role]));

drop policy if exists "staff reads visit photos" on public.site_visit_photos;
drop policy if exists "visit team creates photos" on public.site_visit_photos;
drop policy if exists "photo owners manage photos" on public.site_visit_photos;
drop policy if exists "photo owners delete photos" on public.site_visit_photos;
create policy "authorized staff reads visit photo records" on public.site_visit_photos for select to authenticated
using (private.can_access_site_visit(site_visit_id));
create policy "visit operators create photo records" on public.site_visit_photos for insert to authenticated
with check (created_by = (select auth.uid()) and (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['site_team'::public.app_role]) and exists (select 1 from public.site_visits v where v.id = site_visit_id and v.assigned_to = (select auth.uid())))
));
create policy "visit operators update photo records" on public.site_visit_photos for update to authenticated
using (private.has_role(array['admin'::public.app_role]) or (created_by = (select auth.uid()) and private.can_access_site_visit(site_visit_id)))
with check (private.has_role(array['admin'::public.app_role]) or (created_by = (select auth.uid()) and private.can_access_site_visit(site_visit_id)));
create policy "visit operators delete photo records" on public.site_visit_photos for delete to authenticated
using (private.has_role(array['admin'::public.app_role]) or (created_by = (select auth.uid()) and private.can_access_site_visit(site_visit_id)));

create policy "authorized staff reads measurements" on public.site_visit_measurements for select to authenticated
using (private.can_access_site_visit(site_visit_id));
create policy "visit operators create measurements" on public.site_visit_measurements for insert to authenticated
with check (created_by = (select auth.uid()) and (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['site_team'::public.app_role]) and exists (select 1 from public.site_visits v where v.id = site_visit_id and v.assigned_to = (select auth.uid())))
));
create policy "visit operators update measurements" on public.site_visit_measurements for update to authenticated
using (private.has_role(array['admin'::public.app_role]) or (private.has_role(array['site_team'::public.app_role]) and private.can_access_site_visit(site_visit_id)))
with check (private.has_role(array['admin'::public.app_role]) or (private.has_role(array['site_team'::public.app_role]) and private.can_access_site_visit(site_visit_id)));
create policy "visit operators delete measurements" on public.site_visit_measurements for delete to authenticated
using (private.has_role(array['admin'::public.app_role]) or (private.has_role(array['site_team'::public.app_role]) and private.can_access_site_visit(site_visit_id)));

create policy "authorized staff reads site activity" on public.site_visit_activities for select to authenticated
using (private.can_access_site_visit(site_visit_id));
create policy "visit operators create site activity" on public.site_visit_activities for insert to authenticated
with check (created_by = (select auth.uid()) and (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['site_team'::public.app_role]) and private.can_access_site_visit(site_visit_id))
));

drop policy if exists "staff reads related tasks" on public.tasks;
drop policy if exists "staff creates permitted tasks" on public.tasks;
drop policy if exists "staff updates permitted tasks" on public.tasks;
create policy "staff reads related tasks" on public.tasks for select to authenticated using (
  assigned_to = (select auth.uid()) or created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role])
  or (enquiry_id is not null and private.can_access_enquiry(enquiry_id))
  or (site_visit_id is not null and private.can_access_site_visit(site_visit_id))
  or (project_id is not null and private.can_access_project(project_id))
);
create policy "staff creates permitted tasks" on public.tasks for insert to authenticated with check (
  private.current_user_role() is not null and created_by = (select auth.uid()) and (
    (kind::text = 'enquiry_follow_up' and enquiry_id is not null and private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]) and private.can_access_enquiry(enquiry_id))
    or (kind::text = 'site_visit_follow_up' and site_visit_id is not null and (private.has_role(array['admin'::public.app_role]) or private.has_role(array['site_team'::public.app_role]) and private.can_access_site_visit(site_visit_id)))
    or (kind::text = 'general' and (enquiry_id is null or private.can_access_enquiry(enquiry_id)) and (site_visit_id is null or private.can_access_site_visit(site_visit_id)))
  )
);
create policy "staff updates permitted tasks" on public.tasks for update to authenticated
using (assigned_to = (select auth.uid()) or created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role]))
with check (
  (assigned_to = (select auth.uid()) or created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role]))
  and (enquiry_id is null or private.can_access_enquiry(enquiry_id))
  and (site_visit_id is null or private.can_access_site_visit(site_visit_id))
);

drop policy if exists "visit team views site photos" on storage.objects;
drop policy if exists "visit team uploads site photos" on storage.objects;
drop policy if exists "visit team updates site photos" on storage.objects;
drop policy if exists "visit team deletes site photos" on storage.objects;

create policy "authorized staff views registered site photos" on storage.objects for select to authenticated using (
  bucket_id = 'site-visit-photos' and exists (
    select 1 from public.site_visit_photos p
    where p.storage_path = storage.objects.name and private.can_access_site_visit(p.site_visit_id)
  )
);
create policy "visit operators upload scoped site photos" on storage.objects for insert to authenticated with check (
  bucket_id = 'site-visit-photos'
  and lower(storage.objects.name) ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}/[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\.(jpg|jpeg|png|webp)$'
  and exists (
    select 1 from public.site_visits v
    where v.id::text = (storage.foldername(storage.objects.name))[1]
      and (private.has_role(array['admin'::public.app_role]) or (private.has_role(array['site_team'::public.app_role]) and v.assigned_to = (select auth.uid())))
  )
);
create policy "visit operators update registered site photos" on storage.objects for update to authenticated
using (bucket_id = 'site-visit-photos' and owner_id = (select auth.uid()::text) and exists (select 1 from public.site_visit_photos p where p.storage_path = storage.objects.name and private.can_access_site_visit(p.site_visit_id)))
with check (bucket_id = 'site-visit-photos' and owner_id = (select auth.uid()::text) and exists (select 1 from public.site_visit_photos p where p.storage_path = storage.objects.name and private.can_access_site_visit(p.site_visit_id)));
create policy "visit operators delete registered site photos" on storage.objects for delete to authenticated using (
  bucket_id = 'site-visit-photos' and exists (
    select 1 from public.site_visit_photos p where p.storage_path = storage.objects.name
      and (private.has_role(array['admin'::public.app_role]) or (p.created_by = (select auth.uid()) and private.can_access_site_visit(p.site_visit_id)))
  )
);

update storage.buckets set public = false, file_size_limit = 10485760,
  allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp']
where id = 'site-visit-photos';

comment on table public.site_visit_measurements is 'Structured, unit-aware measurement rows captured during an authorized site visit.';
comment on table public.site_visit_activities is 'Human-readable operational timeline events for a site visit.';
comment on function private.can_access_site_visit(uuid) is 'Assignment-aware site visit authorization shared by table and Storage RLS.';
