-- Universal Pergola Phase 2B: customer, enquiry, follow-up and timeline workflow.

create type public.customer_type as enum ('individual', 'company');
create type public.task_kind as enum ('general', 'enquiry_follow_up');

alter table public.customers
  add column customer_type public.customer_type not null default 'individual',
  add column phone_normalized text,
  add column whatsapp_normalized text,
  add column email_normalized text;

alter table public.enquiries
  add column enquiry_number bigint generated by default as identity (start with 1001),
  add column next_action text,
  add column internal_notes text,
  add constraint enquiries_enquiry_number_key unique (enquiry_number);

alter table public.tasks
  add column kind public.task_kind not null default 'general';

alter table public.customers
  add constraint customers_name_length check (char_length(trim(name)) between 2 and 160),
  add constraint customers_phone_length check (phone is null or char_length(phone) <= 40),
  add constraint customers_whatsapp_length check (whatsapp_number is null or char_length(whatsapp_number) <= 40),
  add constraint customers_email_length check (email is null or char_length(email) <= 254),
  add constraint customers_company_length check (company_name is null or char_length(company_name) <= 160),
  add constraint customers_location_length check (
    (address is null or char_length(address) <= 500)
    and (area is null or char_length(area) <= 120)
    and (emirate is null or char_length(emirate) <= 80)
  ),
  add constraint customers_notes_length check (notes is null or char_length(notes) <= 6000),
  add constraint customers_source_length check (source is null or char_length(source) <= 80);

alter table public.enquiries
  add constraint enquiries_subject_length check (subject is null or char_length(subject) <= 200),
  add constraint enquiries_message_length check (message is null or char_length(message) <= 6000),
  add constraint enquiries_source_length check (source is null or char_length(source) <= 80),
  add constraint enquiries_next_action_length check (next_action is null or char_length(next_action) <= 300),
  add constraint enquiries_internal_notes_length check (internal_notes is null or char_length(internal_notes) <= 6000);

create or replace function private.normalize_phone(value text)
returns text language sql immutable set search_path = '' as $$
  select nullif(regexp_replace(coalesce(value, ''), '[^0-9]', '', 'g'), '')
$$;

create or replace function private.normalize_email(value text)
returns text language sql immutable set search_path = '' as $$
  select nullif(lower(trim(coalesce(value, ''))), '')
$$;

create or replace function private.normalize_customer_contacts()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.phone := nullif(trim(coalesce(new.phone, '')), '');
  new.whatsapp_number := nullif(trim(coalesce(new.whatsapp_number, '')), '');
  new.email := nullif(lower(trim(coalesce(new.email, ''))), '');
  new.phone_normalized := private.normalize_phone(new.phone);
  new.whatsapp_normalized := private.normalize_phone(new.whatsapp_number);
  new.email_normalized := private.normalize_email(new.email);
  return new;
end;
$$;

create trigger customers_normalize_contacts
before insert or update of phone, whatsapp_number, email on public.customers
for each row execute function private.normalize_customer_contacts();

update public.customers
set phone = phone, whatsapp_number = whatsapp_number, email = email;

create index customers_whatsapp_idx on public.customers(whatsapp_normalized)
where whatsapp_normalized is not null and archived_at is null;
create index customers_email_idx on public.customers(email_normalized)
where email_normalized is not null and archived_at is null;
create index customers_phone_normalized_idx on public.customers(phone_normalized)
where phone_normalized is not null and archived_at is null;
create index enquiries_customer_created_idx on public.enquiries(customer_id, created_at desc)
where archived_at is null;
create index enquiries_created_idx on public.enquiries(created_at desc)
where archived_at is null;
create index tasks_enquiry_follow_up_idx on public.tasks(enquiry_id, status, due_at)
where kind = 'enquiry_follow_up' and archived_at is null;

create or replace function private.protect_crm_management_fields()
returns trigger language plpgsql set search_path = '' as $$
begin
  if private.current_user_role() = 'sales'::public.app_role then
    if new.assigned_to is distinct from old.assigned_to then
      raise exception 'Only management can change salesperson assignments';
    end if;
    if new.archived_at is distinct from old.archived_at then
      raise exception 'Only management can change archive status';
    end if;
  end if;
  return new;
end;
$$;

create trigger customers_protect_management_fields
before update on public.customers
for each row execute function private.protect_crm_management_fields();

create trigger enquiries_protect_management_fields
before update on public.enquiries
for each row execute function private.protect_crm_management_fields();

create or replace function private.protect_follow_up_fields()
returns trigger language plpgsql set search_path = '' as $$
begin
  if old.kind = 'enquiry_follow_up'::public.task_kind
     and private.current_user_role() <> 'admin'::public.app_role
     and (
       new.assigned_to is distinct from old.assigned_to
       or new.enquiry_id is distinct from old.enquiry_id
       or new.customer_id is distinct from old.customer_id
       or new.created_by is distinct from old.created_by
       or new.kind is distinct from old.kind
     ) then
    raise exception 'Only management can reassign or relink follow-ups';
  end if;
  return new;
end;
$$;

create trigger tasks_protect_follow_up_fields
before update on public.tasks
for each row execute function private.protect_follow_up_fields();

create or replace function private.log_customer_change()
returns trigger language plpgsql security definer set search_path = '' as $$
declare event_name text;
begin
  if tg_op = 'INSERT' then
    event_name := 'customer.created';
  elsif new.archived_at is not null and old.archived_at is null then
    event_name := 'customer.archived';
  elsif new.archived_at is null and old.archived_at is not null then
    event_name := 'customer.reactivated';
  elsif new.assigned_to is distinct from old.assigned_to then
    event_name := 'customer.salesperson_changed';
  else
    event_name := 'customer.updated';
  end if;
  insert into public.activity_logs(actor_id, event_type, entity_type, entity_id, metadata)
  values ((select auth.uid()), event_name, 'customers', new.id,
    jsonb_strip_nulls(jsonb_build_object('assigned_to', new.assigned_to, 'previous_assigned_to', case when tg_op = 'UPDATE' then old.assigned_to end)));
  return new;
end;
$$;

create or replace function private.log_enquiry_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'INSERT' then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
    values (new.id, 'enquiry_created', 'Enquiry created', (select auth.uid()));
  else
    if new.assigned_to is distinct from old.assigned_to then
      insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
      values (new.id, 'salesperson_assigned', 'Salesperson assignment changed', (select auth.uid()));
    end if;
    if new.status is distinct from old.status then
      insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
      values (new.id, 'status_changed', 'Status changed from ' || replace(old.status::text, '_', ' ') || ' to ' || replace(new.status::text, '_', ' '), (select auth.uid()));
    end if;
    if new.priority is distinct from old.priority then
      insert into public.enquiry_activities(enquiry_id, activity_type, note, created_by)
      values (new.id, 'priority_changed', 'Priority changed from ' || old.priority::text || ' to ' || new.priority::text, (select auth.uid()));
    end if;
  end if;
  return new;
end;
$$;

create or replace function private.log_enquiry_activity_entry()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  insert into public.activity_logs(actor_id, event_type, entity_type, entity_id, metadata)
  values (new.created_by, 'enquiry.' || new.activity_type, 'enquiries', new.enquiry_id,
    jsonb_strip_nulls(jsonb_build_object('activity_id', new.id, 'next_action_at', new.next_action_at)));
  return new;
end;
$$;

create or replace function private.log_follow_up_change()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if new.kind <> 'enquiry_follow_up'::public.task_kind or new.enquiry_id is null then
    return new;
  end if;
  if tg_op = 'INSERT' then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, next_action_at, created_by)
    values (new.enquiry_id, 'follow_up_created', new.title, new.due_at, (select auth.uid()));
  elsif new.status = 'completed'::public.task_status and old.status <> 'completed'::public.task_status then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, next_action_at, created_by)
    values (new.enquiry_id, 'follow_up_completed', new.title, new.due_at, (select auth.uid()));
  elsif new.due_at is distinct from old.due_at then
    insert into public.enquiry_activities(enquiry_id, activity_type, note, next_action_at, created_by)
    values (new.enquiry_id, 'follow_up_rescheduled', new.title, new.due_at, (select auth.uid()));
  end if;
  return new;
end;
$$;

drop trigger if exists enquiries_activity on public.enquiries;
drop trigger if exists tasks_activity on public.tasks;
create trigger customers_crm_activity after insert or update on public.customers
for each row execute function private.log_customer_change();
create trigger enquiries_crm_activity after insert or update on public.enquiries
for each row execute function private.log_enquiry_change();
create trigger enquiry_activities_global_activity after insert on public.enquiry_activities
for each row execute function private.log_enquiry_activity_entry();
create trigger tasks_follow_up_activity after insert or update on public.tasks
for each row execute function private.log_follow_up_change();

create or replace function public.submit_public_enquiry(
  p_name text,
  p_phone text,
  p_message text,
  p_whatsapp_number text default null,
  p_email text default null,
  p_emirate text default null,
  p_product_id uuid default null,
  p_honeypot text default null
)
returns table(enquiry_id uuid, enquiry_number bigint)
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer_record_id uuid;
  enquiry_record public.enquiries%rowtype;
  phone_key text := private.normalize_phone(p_phone);
  email_key text := private.normalize_email(p_email);
  canonical_product_id uuid;
  recent_count integer;
begin
  if nullif(trim(coalesce(p_honeypot, '')), '') is not null then
    raise exception 'Unable to submit this enquiry';
  end if;
  if char_length(trim(coalesce(p_name, ''))) not between 2 and 160 then
    raise exception 'Enter your name';
  end if;
  if phone_key is null or char_length(phone_key) not between 7 and 15 then
    raise exception 'Enter a valid phone number';
  end if;
  if char_length(trim(coalesce(p_message, ''))) not between 5 and 4000 then
    raise exception 'Tell us briefly what you need';
  end if;
  if email_key is not null and email_key !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'Enter a valid email address';
  end if;

  if p_product_id is not null then
    select p.id into canonical_product_id
    from public.products p
    join public.product_categories c on c.id = p.category_id
    where p.id = p_product_id and p.is_published and p.archived_at is null
      and c.is_active and c.archived_at is null;
    if canonical_product_id is null then
      raise exception 'The selected product is no longer available';
    end if;
  end if;

  select count(*) into recent_count
  from public.enquiries e
  join public.customers c on c.id = e.customer_id
  where c.phone_normalized = phone_key and e.created_at > now() - interval '15 minutes';
  if recent_count >= 5 then
    raise exception 'Please wait before sending another enquiry';
  end if;

  select c.id into customer_record_id
  from public.customers c
  where c.phone_normalized = phone_key and c.archived_at is null
  order by c.updated_at desc
  limit 1;

  if customer_record_id is null then
    insert into public.customers(
      name, phone, whatsapp_number, email, emirate, source, customer_type
    ) values (
      trim(p_name), trim(p_phone), nullif(trim(coalesce(p_whatsapp_number, '')), ''),
      email_key, nullif(trim(coalesce(p_emirate, '')), ''),
      case when canonical_product_id is null then 'Website' else 'Website / Catalogue' end,
      'individual'::public.customer_type
    ) returning id into customer_record_id;
  end if;

  insert into public.enquiries(
    customer_id, product_id, enquiry_type, subject, message, source, priority, status
  ) values (
    customer_record_id, canonical_product_id,
    case when canonical_product_id is null then 'general'::public.enquiry_type else 'catalogue'::public.enquiry_type end,
    case when canonical_product_id is null then 'Website enquiry' else 'Catalogue product enquiry' end,
    trim(p_message), case when canonical_product_id is null then 'Website' else 'Website / Catalogue' end,
    'normal'::public.lead_priority, 'new'::public.enquiry_status
  ) returning * into enquiry_record;

  return query select enquiry_record.id, enquiry_record.enquiry_number;
end;
$$;

create or replace function public.create_staff_enquiry(
  p_customer_id uuid,
  p_customer_name text,
  p_phone text,
  p_whatsapp_number text,
  p_email text,
  p_company_name text,
  p_customer_type public.customer_type,
  p_address text,
  p_area text,
  p_emirate text,
  p_source text,
  p_product_id uuid,
  p_subject text,
  p_message text,
  p_priority public.lead_priority,
  p_assigned_to uuid,
  p_follow_up_at timestamptz,
  p_next_action text,
  p_internal_notes text
)
returns table(enquiry_id uuid, customer_id uuid, enquiry_number bigint)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  customer_record_id uuid := p_customer_id;
  enquiry_record public.enquiries%rowtype;
  actor uuid := (select auth.uid());
begin
  if not private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]) then
    raise exception 'CRM access required';
  end if;
  if customer_record_id is null then
    insert into public.customers(
      name, phone, whatsapp_number, email, company_name, customer_type, address, area,
      emirate, source, assigned_to, created_by
    ) values (
      trim(p_customer_name), nullif(trim(coalesce(p_phone, '')), ''),
      nullif(trim(coalesce(p_whatsapp_number, '')), ''), nullif(trim(coalesce(p_email, '')), ''),
      nullif(trim(coalesce(p_company_name, '')), ''), coalesce(p_customer_type, 'individual'::public.customer_type),
      nullif(trim(coalesce(p_address, '')), ''), nullif(trim(coalesce(p_area, '')), ''),
      nullif(trim(coalesce(p_emirate, '')), ''), nullif(trim(coalesce(p_source, '')), ''),
      case when private.current_user_role() = 'admin'::public.app_role then p_assigned_to else actor end,
      actor
    ) returning id into customer_record_id;
  else
    perform 1 from public.customers c where c.id = customer_record_id and c.archived_at is null;
    if not found then raise exception 'Customer not found'; end if;
  end if;

  insert into public.enquiries(
    customer_id, product_id, enquiry_type, subject, message, source, priority, status,
    assigned_to, follow_up_at, next_action, internal_notes, created_by
  ) values (
    customer_record_id, p_product_id,
    case when p_product_id is null then 'manual'::public.enquiry_type else 'catalogue'::public.enquiry_type end,
    nullif(trim(coalesce(p_subject, '')), ''), nullif(trim(coalesce(p_message, '')), ''),
    nullif(trim(coalesce(p_source, '')), ''), coalesce(p_priority, 'normal'::public.lead_priority),
    'new'::public.enquiry_status,
    case when private.current_user_role() = 'admin'::public.app_role then p_assigned_to else actor end,
    p_follow_up_at, nullif(trim(coalesce(p_next_action, '')), ''),
    nullif(trim(coalesce(p_internal_notes, '')), ''), actor
  ) returning * into enquiry_record;

  return query select enquiry_record.id, customer_record_id, enquiry_record.enquiry_number;
end;
$$;

revoke all on function private.normalize_phone(text) from public, anon;
revoke all on function private.normalize_email(text) from public, anon;
revoke all on function private.normalize_customer_contacts() from public, anon, authenticated;
revoke all on function private.protect_crm_management_fields() from public, anon, authenticated;
revoke all on function private.protect_follow_up_fields() from public, anon, authenticated;
revoke all on function private.log_customer_change() from public, anon, authenticated;
revoke all on function private.log_enquiry_change() from public, anon, authenticated;
revoke all on function private.log_enquiry_activity_entry() from public, anon, authenticated;
revoke all on function private.log_follow_up_change() from public, anon, authenticated;
grant execute on function private.normalize_phone(text), private.normalize_email(text) to authenticated;

revoke all on function public.submit_public_enquiry(text, text, text, text, text, text, uuid, text) from public, authenticated;
grant execute on function public.submit_public_enquiry(text, text, text, text, text, text, uuid, text) to anon;
revoke all on function public.create_staff_enquiry(uuid, text, text, text, text, text, public.customer_type, text, text, text, text, uuid, text, text, public.lead_priority, uuid, timestamptz, text, text) from public, anon;
grant execute on function public.create_staff_enquiry(uuid, text, text, text, text, text, public.customer_type, text, text, text, text, uuid, text, text, public.lead_priority, uuid, timestamptz, text, text) to authenticated;
grant usage, select on sequence public.enquiries_enquiry_number_seq to authenticated;

drop policy if exists "profiles read self or admin" on public.profiles;
create policy "active staff reads directory" on public.profiles for select to authenticated
using (private.has_role(array['admin'::public.app_role]) or (status = 'active'::public.profile_status and private.current_user_role() is not null));

drop policy if exists "sales manages customers" on public.customers;
create policy "crm staff creates customers" on public.customers for insert to authenticated
with check (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['sales'::public.app_role]) and created_by = (select auth.uid()) and (assigned_to is null or assigned_to = (select auth.uid())))
);
create policy "crm staff updates customers" on public.customers for update to authenticated
using (private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]))
with check (private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]));

drop policy if exists "sales manages enquiries" on public.enquiries;
create policy "crm staff creates enquiries" on public.enquiries for insert to authenticated
with check (
  private.has_role(array['admin'::public.app_role])
  or (private.has_role(array['sales'::public.app_role]) and created_by = (select auth.uid()) and (assigned_to is null or assigned_to = (select auth.uid())))
);
create policy "crm staff updates enquiries" on public.enquiries for update to authenticated
using (private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]))
with check (private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]));

drop policy if exists "authors update enquiry activity" on public.enquiry_activities;
create policy "authors update enquiry activity" on public.enquiry_activities for update to authenticated
using (private.can_access_enquiry(enquiry_id) and (created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role])))
with check (private.can_access_enquiry(enquiry_id) and (created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role])));

drop policy if exists "staff reads related tasks" on public.tasks;
drop policy if exists "staff creates tasks" on public.tasks;
drop policy if exists "assignees update tasks" on public.tasks;
drop policy if exists "task owners delete tasks" on public.tasks;
create policy "staff reads related tasks" on public.tasks for select to authenticated using (
  assigned_to = (select auth.uid()) or created_by = (select auth.uid())
  or private.has_role(array['admin'::public.app_role])
  or (enquiry_id is not null and private.can_access_enquiry(enquiry_id))
  or (project_id is not null and private.can_access_project(project_id))
);
create policy "staff creates permitted tasks" on public.tasks for insert to authenticated with check (
  private.current_user_role() is not null and created_by = (select auth.uid())
  and (
    enquiry_id is null
    or (private.has_role(array['admin'::public.app_role, 'sales'::public.app_role]) and private.can_access_enquiry(enquiry_id))
  )
);
create policy "staff updates permitted tasks" on public.tasks for update to authenticated
using (assigned_to = (select auth.uid()) or created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role]))
with check (
  (assigned_to = (select auth.uid()) or created_by = (select auth.uid()) or private.has_role(array['admin'::public.app_role]))
  and (enquiry_id is null or private.can_access_enquiry(enquiry_id))
);
create policy "management deletes tasks" on public.tasks for delete to authenticated
using (private.has_role(array['admin'::public.app_role]));

comment on function public.submit_public_enquiry is 'Narrow anonymous entry point: validates, rate limits by normalized phone, safely reuses an exact-phone customer and creates an enquiry atomically.';
comment on function public.create_staff_enquiry is 'Authenticated transactional entry point for creating a manual enquiry with an existing or inline customer.';
