import { PageHeading } from "@/components/ui/page-heading";
import { formatDate } from "@/lib/crm/presentation";
import { formatMoney } from "@/lib/quotations/money";
import { getProjects } from "@/lib/projects/queries";
import { getAssets, getOperationsLedger } from "@/lib/operations/queries";
import { getFinanceDashboardSummary } from "@/lib/payments/queries";
import { ExpenseForm, WageForm } from "@/components/dashboard/operations-forms";
import { BillUploader } from "@/components/dashboard/bill-uploader";
import Link from "next/link";
import { requireModuleAccess } from "@/lib/auth/dal";

export default async function AccountsPage() {
  await requireModuleAccess("accounts");
  const [ledger, projects, assets, payments] = await Promise.all([getOperationsLedger(), getProjects({}), getAssets(), getFinanceDashboardSummary()]);
  const projectOptions = projects.map((p) => ({ id: p.id, project_number: p.project_number }));
  const projectTotal = ledger.expenses.filter((e)=>e.scope === "project").reduce((sum,e)=>sum+Number(e.amount),0);
  const workshopTotal = ledger.expenses.filter((e)=>e.scope === "workshop").reduce((sum,e)=>sum+Number(e.amount),0);
  return <div className="space-y-7"><PageHeading title="Accounts" description="Internal cost control, customer receivables, and private purchase records." action={<Link href="/dashboard/assets" className="inline-flex min-h-11 items-center rounded-md border border-line bg-paper px-4 text-sm font-semibold hover:bg-limestone">Assets & machinery</Link>} />
    <section className="grid grid-cols-2 gap-px overflow-hidden rounded-lg border border-line bg-line md:grid-cols-4"><div className="bg-paper p-4"><p className="text-xs text-stone">Project expenses</p><p className="mt-2 text-xl font-semibold">{formatMoney(projectTotal)}</p></div><div className="bg-paper p-4"><p className="text-xs text-stone">Workshop expenses</p><p className="mt-2 text-xl font-semibold">{formatMoney(workshopTotal)}</p></div><div className="bg-paper p-4"><p className="text-xs text-stone">Labour wages</p><p className="mt-2 text-xl font-semibold">{formatMoney(ledger.wages.reduce((sum,w)=>sum+Number(w.amount),0))}</p></div><div className="bg-paper p-4"><p className="text-xs text-stone">Private bills</p><p className="mt-2 text-xl font-semibold">{ledger.bills.length}</p></div></section>
    <section className="grid gap-4 md:grid-cols-3" aria-label="Accounts areas"><Link href="/dashboard/payments" className="group rounded-lg bg-graphite p-5 text-white transition-colors hover:bg-charcoal"><p className="text-xs font-medium text-white/55">Money in</p><h2 className="mt-2 text-lg font-semibold">Customer Payments</h2><p className="mt-1 text-xl font-semibold text-brass">{formatMoney(Number(payments?.received || 0))}</p><span className="mt-4 inline-flex text-sm font-semibold text-white/75 group-hover:text-white">View customer payments →</span></Link><div className="rounded-lg border border-line bg-paper p-5"><p className="text-xs font-medium text-stone">Money out / internal cost</p><h2 className="mt-2 text-lg font-semibold">Operating costs</h2><p className="mt-1 text-sm text-stone">Project expenses, workshop expenses, and labour wages stay in this Accounts workspace.</p></div><Link href="/dashboard/assets" className="group rounded-lg border border-line bg-paper p-5 transition-colors hover:border-brass/60 hover:bg-limestone"><p className="text-xs font-medium text-stone">Supporting</p><h2 className="mt-2 text-lg font-semibold">Assets & machinery</h2><p className="mt-1 text-sm text-stone">Equipment, planned purchases, and private bills.</p><span className="mt-4 inline-flex text-sm font-semibold text-brass-dark group-hover:text-graphite">Open asset register →</span></Link></section>
    <div className="grid gap-7 xl:grid-cols-2"><section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-lg font-semibold">Project / workshop expenses</h2><p className="mt-1 text-sm text-stone">Separate from customer payment balances.</p><div className="mt-5"><ExpenseForm projects={projectOptions}/></div></section><section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-lg font-semibold">Labour wages</h2><p className="mt-1 text-sm text-stone">Named workers or crews; no Auth account required.</p><div className="mt-5"><WageForm projects={projectOptions}/></div></section></div>
    <section className="rounded-lg border border-line bg-paper p-5"><h2 className="text-lg font-semibold">Purchase bills</h2><p className="mt-1 text-sm text-stone">Upload a private bill from a phone camera, file picker, or scanner-produced file.</p><div className="mt-5"><BillUploader expenses={ledger.expenses.map(({id,description})=>({id,description}))} assets={assets.map(({id,name,asset_code})=>({id,name,asset_code}))}/></div></section>
    <section className="rounded-lg border border-line bg-paper p-5"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recent internal entries</h2><p className="mt-1 text-sm text-stone">Private operational ledger; customer receipts remain in Payments.</p></div><span className="text-xs text-stone">{ledger.expenses.length} expenses · {ledger.wages.length} wages</span></div><div className="mt-4 divide-y divide-line">{ledger.expenses.slice(0,12).map((item)=><div key={item.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><p className="text-sm font-medium">{item.description}</p><p className="text-xs text-stone">{item.scope === "project" ? item.project?.project_number || "Project" : "Workshop / common"} · {item.category} · {formatDate(item.expense_date)}</p></div><strong>{formatMoney(Number(item.amount), item.currency)}</strong></div>)}{!ledger.expenses.length ? <p className="py-7 text-center text-sm text-stone">No internal expenses recorded.</p>:null}</div></section>
  </div>;
}
